#!/bin/bash
# check_transfer.sh — verify the files the pipeline needs arrived intact and in the right place.
# Run from INSIDE the project folder (the one holding _targets.R), whatever it is called, e.g.:
#   cd ~/bridgeslab/alzheimers-mr && bash pipeline/check_transfer.sh
# calcium-cholesterol files are expected in the SIBLING folder ../calcium-cholesterol/.
# Generated by pipeline/make_transfer_check.sh on the Mac; lines are "md5  path-as-on-the-Mac".
[[ -f _targets.R ]] || { echo "Run this from the folder that contains _targets.R"; exit 1; }
ok=0; missing=0; bad=0
while read -r sum path; do
  [[ -z "$path" ]] && continue
  case "$path" in
    alzheimers/*)          path="${path#alzheimers/}" ;;
    calcium-cholesterol/*) path="../$path" ;;
  esac
  if [[ ! -f "$path" ]]; then echo "MISSING   $path"; missing=$((missing+1)); continue; fi
  got=$(md5sum "$path" | cut -d' ' -f1)
  if [[ "$got" == "$sum" ]]; then ok=$((ok+1)); else echo "DIFFERENT $path"; bad=$((bad+1)); fi
done <<'MANIFEST'
61f84451076fe2ce70bf547eabf457b3 alzheimers/_targets.R
d029145ee895f68e54719ed36b9ea68b alzheimers/smoking/results/indexevent_slopehunter_fits.csv
ea5e00d768d3447928f16858486d9b25 alzheimers/R/fits/kunkle_lifespan_slopehunter_fits.csv
faacc65d63e056c415d5ddea5711ad79 alzheimers/R/fit_selection_slope.R
6c8c54aba4b17c887a8be2660d4346ec alzheimers/data/cache/EUR.bed
4ce5e9160119594bca775074b3c55a23 alzheimers/data/cache/EUR.bim
7dc68f97189d131278b1e3c39951dbf4 alzheimers/data/cache/EUR.fam
0c3b5d3f6f5ae48656f746676715cb95 calcium-cholesterol/R/robust_mr_helpers.R
e1372a59749eb1f92f7f6931c075f5ac calcium-cholesterol/raw_data/reference/w_hm3.snplist
de479e68dc868de1713178a50a38b032 alzheimers/data/cache/sumstats/AD_kunkle_harmonised.tsv.gz
69ca4f96733ceb241cf2df5cbc945fb3 alzheimers/data/cache/sumstats/LIFESPAN_pilling_harmonised.tsv.gz
99c65705dde7ea2b482f28e814c2ae40 alzheimers/pipeline/run_greatlakes.sbatch
156817d6c5f67aa30dc727eb7f842830 alzheimers/pipeline/make_transfer_check.sh
3ca12a4496247f4729e8ef303c7606df alzheimers/pipeline/R/apss.R
a657296110b40ca48f2cdf30e6ee0dff alzheimers/pipeline/R/mraid.R
c11032e59640008036209292eb5d8651 alzheimers/pipeline/R/classical.R
1c535210875108ec8213a31d19ef8251 alzheimers/pipeline/R/plots.R
dc42797b451e0bc2d9f000d19df33289 alzheimers/pipeline/R/instruments.R
b70177192ffe6b0b113e69ff0680b327 alzheimers/pipeline/R/latent.R
fcc681f75557d9a459f2e8187752f411 alzheimers/pipeline/R/fetch.R
41e512bb5ae55ae6bab0cd513a4a1b6e alzheimers/pipeline/R/cause.R
4ca2549387fdb6a1d1ea7037b02fc573 alzheimers/pipeline/R/pipeline.R
260372e36d505176b1dc1aee457de774 alzheimers/pipeline/R/selection.R
822ee1bb3ed4c4e2a2171c9afdeed7a5 alzheimers/pipeline/R/stability.R
7915a76b9c2153c2fb852c9df9967a7e alzheimers/pipeline/R/read.R
7a11e7604f07a3a48d3f6eba26ebc9a0 alzheimers/pipeline/README.md
f1a79729391a61d9e75204729402458e alzheimers/pipeline/config.yml
ad1d81ec23d9f689b93450a4c6384510 alzheimers/data/cache/gwas/ukb-b-2303.vcf.gz
0ce87533d04ad61a3dae744cd72473b8 alzheimers/data/cache/gwas/ukb-b-13354.vcf.gz
48362a9b48a488042d8fc0515fb405ab alzheimers/data/cache/gwas/ebi-a-GCST005186.vcf.gz
924703828e93bd508b9c12fc4d155b90 alzheimers/data/cache/gwas/ebi-a-GCST006867.vcf.gz
e974972d738bfb948f87649659d39840 alzheimers/data/cache/gwas/ukb-b-19393.vcf.gz
213e85bd46c81ea3cf7399d544fcb226 alzheimers/data/cache/gwas/ebi-a-GCST90002227.vcf.gz
25d748ae8c69f9c7dab57c211c5cb208 alzheimers/data/cache/gwas/ebi-a-GCST90000025.vcf.gz
31e194e7390586ec7b645e213f57506c alzheimers/data/cache/gwas/ebi-a-GCST90027158.vcf.gz
691d0021b6b06bd1b8d77af7cb06baee alzheimers/data/cache/gwas/ieu-b-4761.vcf.gz
37d98a5963cdaea727177bc766896710 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.18.l2.M
f69d436d06b27bfe1780b1dedfe743e4 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.4.log
59cbe69c5634f5647cdd07b3dcc9c936 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.7.l2.M
a00960339414fd86589b7f0f5c164dd8 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.10.l2.ldscore.gz
a7faf8260fdc2f521456ce6086b60ad1 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.22.l2.M
916d2c90df2920c2e96fd1e7251b0db5 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.14.l2.ldscore.gz
45ad02aa7d116229e35dc92680a091bd calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.13.l2.M_5_50
2b8584bde4259a3b525a4a6ac2c51478 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.9.l2.M_5_50
15dbe04db8862708527c994e7b05beb0 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.5.log
3cab7a9a321af1f65acc6ba028bd86b5 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.14.l2.M
1428b59b878c0ede0c71ef05bdbbebc9 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.7.log
94448339f705e21a3ec95437cb666cf4 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.4.l2.M_5_50
6d48c443dfdb8dab0364ee1e02d42108 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.6.log
cacde6a1cc32548994e15adb9dbb441b calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.2.log
92a8ea326fb83b070a0d2cedd4b3ae01 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.9.l2.ldscore.gz
02737c9452a0cbb8f0e7ee65fc59f41a calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.15.l2.M_5_50
21c9264c0e192ea240391a99d040cce3 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.20.l2.M_5_50
eab3fed143f692eca6e8cb3eb12aa05a calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.3.log
6ba18d020d6d71d11d788c26d96b2ee0 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.15.l2.M
720cc9e0cc291f2288c3ba8484e2017d calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.1.log
e72191153826e64a6460136f8ec23880 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.13.l2.ldscore.gz
72b18c790695c4f38d33350da64576dc calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.2.l2.M_5_50
d0f42210b8cc9e6934cb439ac79dcc29 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.18.l2.M_5_50
566b6c50f76f34331c6f05075a0bb957 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.6.l2.M
c83e8e258c8f35524792f0bd70a55cc5 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.19.l2.M
aea7a988fbafa508c89bcb10fa6a4526 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.17.l2.ldscore.gz
bcb6301ce40a627cca6e0f8e830b0c90 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.12.l2.M
d157d68bdc59896e8b949e5ec61ca6fc calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.14.log
df06a68ac22c8ddbd83848e88e44802e calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.12.l2.M_5_50
da49827c764a95b82647937a3ffceeb0 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.8.l2.M_5_50
6398c371417e41d9af2e5b913c147e1d calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.15.log
b49263301e0a12ef1aa0bf40ccee367f calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.20.l2.ldscore.gz
4fcfd7e1a7a03c899f4304e54fc614a0 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.19.l2.ldscore.gz
689a0d65f91e4a3a9683f439fefed921 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.7.l2.ldscore.gz
aa02c35df7699d3c4cb3ba24c412e0d4 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.1.l2.M
85d944ff8784db5c1d1df306aaf5b82a calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.17.log
49049442133e483274611a1b7922c19f calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.5.l2.M_5_50
39d205212af3694a78d27577f7cb7720 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.3.l2.ldscore.gz
bd9125295266a0a661b062ef10cab186 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.16.log
daf7204f035c6e6ae6cc1ce8151f823f calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.4.l2.ldscore.gz
35ab805d6fa567b878a63fb5c67336a9 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.14.l2.M_5_50
a48b7095c28b3cc78b6d948b957eb892 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.12.log
ac0e6a6bc027e428a738ef91e322b6f1 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.21.l2.M_5_50
766a4d7d7c3eaa9d4a1ac44a5f9fc8c4 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.13.log
6a3371ea1a5efe4fa7a7d25d85868a69 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.3.l2.M_5_50
f39be6436aa873fdc42fe88ffdb956ae calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.19.l2.M_5_50
3a5582ab299bc11fdd2beeca9f029d90 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.11.log
84d2c7af77410c26a158debdb96d69e8 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.10.log
1492ddc09884a9d078917164c768c0f5 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.13.l2.M
28bc2dbc4ff5ec70e33e9a2621eb382d calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.21.log
9e3e928546e5355dd509bc1341cf0cbc calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.11.l2.M_5_50
5c66f5bd55dd85b0903a0a377b9996f4 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.1.l2.ldscore.gz
3095f16b773f96883cb0deed3cf54712 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.20.log
8f8a67f7b41f17f12f4676825244323b calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.5.l2.ldscore.gz
0e36b80f8c126eeeb44354a16ca24a2d calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.10.l2.M
870e10026f69742f691aba33873f05dc calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.22.log
fa81a278841c05f2127ec2c220364510 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.6.l2.M_5_50
2a52febb5beac1fa990c8e4066d70090 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.22.l2.ldscore.gz
e2a2b74444fb86f1b7f418fd764664ae calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.3.l2.M
7766fcdbefee42ea66784df9abe2a93d calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.18.l2.ldscore.gz
767e0e8d86db32f0d24b5af856986f5d calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.2.l2.M
a95a85c5a18b69660e6ff13e21b9f954 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.22.l2.M_5_50
8d7dd0e2db22e8d2c61c8f6b9614bb59 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.21.l2.ldscore.gz
41549485189475f50dd26470fddf71bb calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.17.l2.M_5_50
beec02206c2abe1359b3f347c8496ab0 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.11.l2.M
b85d59cf3174aa06c64513bafa27940c calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.18.log
e873135c963d9684fa50e9371e56057d calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.2.l2.ldscore.gz
db7245370b65010c777d5d8bf6b6176b calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.19.log
2c8372dcf3b20c8418018568a80aa25d calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.6.l2.ldscore.gz
6838471f96375a6b436b1a4161d3b89f calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.10.l2.M_5_50
d04f8c23b50a81e9ad2b84714f6bb99e calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.20.l2.M
188243280dd007f112ef57135f543443 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.5.l2.M
768a0a5dac775605de34219c8c3ae1d1 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.8.l2.ldscore.gz
8f276b96db5e01524aa5332be023016b calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.16.l2.ldscore.gz
10e2c35a21da206db1e50292b016125f calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.7.l2.M_5_50
12abd64d9b86813c72840284020ef200 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.9.l2.M
3f6dfd5eb0eb2747cd75dfcb9b40774e calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.12.l2.ldscore.gz
17b3cf311c3b2aae6ad4fa825b3fdbea calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.16.l2.M
0653aaf98a9bab8ccc70ed48bb89712f calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.17.l2.M
9add6b410655dc8cc1a2f4cb2e045707 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.15.l2.ldscore.gz
0eed117502a9b8153524d5bd97c0ae98 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.8.l2.M
bb3af34bc92e72482cad5a7a3d8234d4 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.11.l2.ldscore.gz
3562df7a8e3b774c77bda4c3face4ce0 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.16.l2.M_5_50
a7fcbd46bf5d81e8c7610291a601fa35 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.8.log
2ec807732606f6789181e945b646000d calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.4.l2.M
dd8bae8065346bd5181414af680fda69 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.21.l2.M
fb0c78d484aaf78e09ea6a26edde11c7 calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.1.l2.M_5_50
83516aafc58064aaaa198ee5127da92c calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore/LDscore.9.log
MANIFEST
echo
echo "OK: $ok   MISSING: $missing   DIFFERENT: $bad"
if (( missing + bad == 0 )); then echo "All files present and identical. Next: the tar_outdated pre-flight check."
else echo "Fix the files listed above before submitting (a DIFFERENT file usually means an incomplete upload)."; fi
