#!/bin/bash
# make_transfer_check.sh — (Mac) regenerate pipeline/check_transfer.sh with current checksums of
# every file the Great Lakes run needs. Run from alzheimers/ after any change, then upload the
# changed files plus pipeline/check_transfer.sh and run it on the cluster.
set -euo pipefail
cd "$(dirname "$0")/../.."          # -> Human Genetics/
OUT=alzheimers/pipeline/check_transfer.sh
{
cat <<'EOF'
#!/bin/bash
# check_transfer.sh — verify the files the pipeline needs arrived intact and in the right place.
# Run from INSIDE the project folder (the one holding _targets.R), whatever it is called, e.g.:
#   cd ~/bridgeslab/alzheimers-mr && bash pipeline/check_transfer.sh
# calcium-cholesterol files are expected in the SIBLING folder ../calcium-cholesterol/.
# Generated by pipeline/make_transfer_check.sh on the Mac; lines are "md5  path-as-on-the-Mac".
[[ -f _targets.R ]] || { echo "Run this from the folder that contains _targets.R"; exit 1; }
ok=0; missing=0; bad=0
while read -r sum path; do
  [[ -z "$path" ]] && continue
  case "$path" in
    alzheimers/*)          path="${path#alzheimers/}" ;;
    calcium-cholesterol/*) path="../$path" ;;
  esac
  if [[ ! -f "$path" ]]; then echo "MISSING   $path"; missing=$((missing+1)); continue; fi
  got=$(md5sum "$path" | cut -d' ' -f1)
  if [[ "$got" == "$sum" ]]; then ok=$((ok+1)); else echo "DIFFERENT $path"; bad=$((bad+1)); fi
done <<'MANIFEST'
EOF
for f in alzheimers/_targets.R alzheimers/smoking/results/indexevent_slopehunter_fits.csv \
         alzheimers/R/fits/kunkle_lifespan_slopehunter_fits.csv alzheimers/R/fit_selection_slope.R \
         alzheimers/data/cache/EUR.bed alzheimers/data/cache/EUR.bim alzheimers/data/cache/EUR.fam \
         calcium-cholesterol/R/robust_mr_helpers.R calcium-cholesterol/raw_data/reference/w_hm3.snplist \
         alzheimers/data/cache/sumstats/AD_kunkle_harmonised.tsv.gz \
         alzheimers/data/cache/sumstats/LIFESPAN_pilling_harmonised.tsv.gz; do md5 -r "$f"; done
find alzheimers/pipeline -type f ! -name check_transfer.sh ! -name '.DS_Store' -exec md5 -r {} \;
find alzheimers/data/cache/gwas -type f -name '*.vcf.gz' ! -name '*_raw.vcf.gz' -exec md5 -r {} \;
find calcium-cholesterol/raw_data/reference/eur_w_ld_chr/LDscore -type f -exec md5 -r {} \;
# The _targets/ store is checked only with --with-store: once a run has happened on the cluster,
# the CLUSTER's store is the complete one and must not be overwritten from the Mac.
if [[ "${1:-}" == "--with-store" ]]; then
  find alzheimers/_targets -type f ! -name '.DS_Store' ! -path '*/workspaces/*' ! -path '*/scratch/*' \
       ! -name progress ! -name process ! -name crew -exec md5 -r {} \;
fi
cat <<'EOF'
MANIFEST
echo
echo "OK: $ok   MISSING: $missing   DIFFERENT: $bad"
if (( missing + bad == 0 )); then echo "All files present and identical. Next: the tar_outdated pre-flight check."
else echo "Fix the files listed above before submitting (a DIFFERENT file usually means an incomplete upload)."; fi
EOF
} > "$OUT"
chmod +x "$OUT"
echo "wrote $OUT: $(grep -c -E '^[0-9a-f]{32} ' "$OUT") files"
