---
title: "Relationship between calcium and cholesterol in BXD Mice"
author: "Dave Bridges"
date: "December 1, 2022"
output:
  html_document:
    highlight: tango
    keep_md: yes
    number_sections: yes
    toc: yes
  pdf_document:
    highlight: tango
    keep_tex: yes
    number_sections: yes
    toc: yes
---

```{r global_options, include=FALSE}
library(knitr)
#figures makde will go to directory called figures, will make them as both png and pdf files 
opts_chunk$set(fig.path='figures/',
               echo=TRUE, warning=FALSE, message=FALSE,dev=c('png','pdf'))
options(scipen = 2, digits = 3)
# set echo and message to TRUE if you want to display code blocks and code output respectively

knitr::knit_hooks$set(inline = function(x) {
  knitr:::format_sci(x, 'md')
})


superpose.eb <- function (x, y, ebl, ebu = ebl, length = 0.08, ...)
  arrows(x, y + ebu, x, y - ebl, angle = 90, code = 3,
  length = length, ...)

  
se <- function(x) sd(x, na.rm=T)/sqrt(length(x))

#load these packages, nearly always needed
library(tidyr)
library(dplyr)

# sets maize and blue color scheme
color.scheme <- c('#00274c', '#ffcb05')
```

# Purpose

To analyze cholesterol levels from diversity outbred mice, identifying predictors of elevated choelsterol.

# Experimental Details

This analysis uses data from the Andreux et al dataset

# Raw Data

```{r datafiles}
ca.female.filename <- 'BXD_12844.csv'	
ca.male.filename <- 'BXD_12914.csv' 
chol.male.filename <- 'BXD_12951.csv'	
chol.female.filename <- 'BXD_12881.csv'
```


```{r data-input}
library(readr) #loads the readr package


ca.f.data <- read_csv(ca.female.filename, skip=10) %>% mutate(Sex="F",Measure="Ca")
ca.m.data <- read_csv(ca.male.filename, skip=10) %>% mutate(Sex="M",Measure="Ca")
chol.f.data <- read_csv(chol.female.filename, skip=10) %>% mutate(Sex="F",Measure="Chol")
chol.m.data <- read_csv(chol.male.filename, skip=10) %>% mutate(Sex="M",Measure="Chol")

combined.data <-
  left_join(bind_rows(ca.f.data,ca.m.data),
            bind_rows(chol.f.data,chol.m.data),
            by=c("Name","Sex"),
            suffix=c("_ca","_chol")) %>%
  mutate(Chol=Value_chol*38.665,
         Chol.se = SE_chol*38.665) %>% #convert to mg/dL
  mutate(Ca = Value_ca*4.005,
         Ca.se = SE_ca*4.005)#convert to mg/dL

```

# Sample Sizes

```{r sample-sizes}
combined.data %>%
  mutate(Ca.Data = !(is.na(Ca)),
         Chol.Data = !(is.na(Chol))) %>%
  group_by(Sex,Ca.Data,Chol.Data) %>%
  count %>%
  kable(caption="Number of strains for BXD Ca/Chol associations")

combined.data %>%
  mutate(Total.Mice = N_ca + N_chol) %>%
  group_by(Sex) %>%
  summarize(All.Mice = sum(Total.Mice)) %>%
  kable(caption="Number of strains for BXD Ca/Chol associations")
```

# Analysis of BXD 

```{r bxd-ca-chol-correlation}
library(ggplot2)
library(ggrepel)
combined.data %>%
  ggplot(aes(y=Chol,x=Ca)) +
  geom_point() +
  geom_smooth(method="lm",color="grey") +
  labs(y="Cholesterol (mg/dL)",
       x="Calcium (mg/dL)",
       title="BXD Strains") +
  #geom_label_repel(aes(label=Name)) +
  facet_grid(.~Sex) +
  theme_classic() +
  theme(text=element_text(size=16))

combined.data %>%
  ggplot(aes(y=Chol,x=Ca)) +
  geom_point() +
  geom_errorbar(aes(ymin=Chol-Chol.se,
                    ymax=Chol+Chol.se)) +
  geom_errorbarh(aes(xmin=Ca-Ca.se,
                    xmax=Ca-Ca.se)) +
  geom_smooth(method="lm",color="grey") +
  labs(y="Cholesterol (mg/dL)",
       x="Calcium (mg/dL)",
       title="BXD Strains") +
  #geom_label_repel(aes(label=Name)) +
  facet_grid(.~Sex) +
  theme_classic() +
  theme(text=element_text(size=16))


library(broom)
with(combined.data, cor.test(Ca,Chol, method="spearman"))  %>%
  tidy %>%
  kable(caption="Overall association between calcium and cholesterol in BXD mice")

with(combined.data %>% filter(Sex=="M"), cor.test(Ca,Chol, method="spearman"))  %>%
  tidy %>%
  kable(caption="Association between calcium and cholesterol in BXD male mice")

with(combined.data %>% filter(Sex=="F"), cor.test(Ca,Chol, method="spearman"))  %>%
  tidy %>%
  kable(caption="Association between calcium and cholesterol in BXD female mice")

lm(Chol ~ Sex + Ca, data=combined.data) %>% tidy %>%
  kable(caption="Multivariate regression of Calcium and Cholesterol Associations")

lm(Chol ~ Sex + Ca, data=combined.data) %>% glance %>%
  kable(caption="Multivariate regression of Calcium and Cholesterol Associations")

lm(Chol ~ Sex + Ca + Sex:Ca, data=combined.data) %>% tidy %>%
  kable(caption="Multivariate regression of Calcium and Cholesterol Associations, testing for modification by sex")
```

# Session Information

```{r session-information, echo=T}
sessionInfo()
```

