---
title: "Liver mRNA TWAS Analysis"
author: "Dave Bridges"
format: html
editor: source
---

```{r load}
library(readr)
library(dplyr)
library(tidyr)
library(broom)
library(tidyverse)

rna.datatfile <- 'dataset.mrna.Svenson_DO_HFD.v12.Rds'
all.data <- readRDS(rna.datatfile)

rna.data.raw <- all.data$data$raw %>% as.data.frame()

library(janitor)
rna.data.raw %>% t %>% as.data.frame -> rna.data

gene.annotation <- all.data$annot.mrna %>%
  mutate(start.true = start*1E6,
         end.true = end*1E6)
```

Pulled out phenotype data

```{r collecting-phenotype-data}
phenotype.datatfile <- 'dataset.phenotype.Svenson_DO_HFD.v12.Rds'
phenotype.data <- readRDS(phenotype.datatfile)

library(tibble)
chol.phenotypes <- 
  phenotype.data$data$raw %>% 
  as.data.frame %>%
  select(chol2) %>%
  mutate(chol2.scale = scale(chol2,center=T)) %>%
  rownames_to_column("ID")

library(forcats)
group.data <- 
  phenotype.data$annot.samples %>%
  select(mouse.id,sex,diet) %>% 
  column_to_rownames('mouse.id') %>% 
  mutate_all(as.factor) %>%
  rownames_to_column('ID')

pheno.data.all <- full_join(chol.phenotypes,group.data,by="ID")
```

## Linear Models with Cholesterol as Dependent Variable

```{r chol-dep-lm}
#| message: false
lm.results <- data.frame()

for (gene in rownames(rna.data)){
gene.data <- 
  rna.data[gene,] %>% 
  t %>% 
  as.data.frame %>% 
  rownames_to_column('ID') %>% 
  left_join(pheno.data.all)

gene.lm <- lm(chol2~log2(get(gene)+1),data=gene.data)

lm.results <- bind_rows(lm.results, list(ID=gene, 
                                         beta=tidy(gene.lm)[2,]$estimate,
                                         se=tidy(gene.lm)[2,]$std.error,
                                         pval=tidy(gene.lm)[2,]$p.value,
                                         r2 = glance(gene.lm)$adj.r.squared))
}

library(knitr)

lm.results.anno <- lm.results %>%
  mutate(padj=p.adjust(pval, method="BH")) %>%  
  left_join(select(gene.annotation, gene.id,symbol,chr,start.true,end.true),
                             by=c('ID'='gene.id'))

lm.results.anno %>% arrange(pval) %>% head(25) %>% kable(caption="Top 25 associations using linear models, no covariates")

lm.results.anno %>% write_csv("Cholesterol - Expression Associations - Linear Model.csv")
```

### Plots for Linear Models

These are plots for the top 10 cholesterol-liver mRNA associations using a linear model with no covariates.

```{r chol-lm-plots}
#| message: false
top.genes <- lm.results.anno %>% arrange(pval) %>% head(25) %>% pull(ID)

for (gene in top.genes) {

gene.data <- 
  rna.data[gene,] %>% 
  t %>% 
  as.data.frame %>% 
  rownames_to_column('ID') %>% 
  left_join(pheno.data.all)

plot <- ggplot(gene.data %>% filter(!(is.na(sex))),
       aes(y=chol2,x=get(gene))) +
  geom_point(aes(col=sex)) +
  stat_smooth(method="lm") +
  labs(title=lm.results.anno %>% filter(ID==gene) %>% pull(symbol),
       x="Liver mRNA Expression",
       y="Cholesterol (mg/dL)") +
  theme_classic(base_size=16) +
  theme(legend.position=c("0.8,0.8"))

print(plot)
}
```

## Generalized Additive Models

Using generalized aditive models which do not presume a linear relationships

```{r gchol-dep-gam}
library(mgcv)

#| message: false
lm.results <- data.frame()

for (gene in rownames(rna.data)[1:1000]){
gene.data <- 
  rna.data[gene,] %>% 
  t %>% 
  as.data.frame %>% 
  rownames_to_column('ID') %>% 
  left_join(pheno.data.all)

gene.lm <- gam(chol2~s(get(gene)),data=gene.data)

lm.results <- bind_rows(lm.results, list(ID=gene, 
                                         edf=tidy(gene.lm)[1,]$edf,
                                         ref.df=tidy(gene.lm)[1,]$ref.df,
                                         pval=tidy(gene.lm)[1,]$p.value,
                                         r2 = glance(gene.lm)$adj.r.squared))
}

library(knitr)

lm.results.anno <- lm.results %>%
  mutate(padj=p.adjust(pval, method="BH")) %>%  
  left_join(select(gene.annotation, gene.id,symbol,chr,start.true,end.true),
                             by=c('ID'='gene.id'))

lm.results.anno %>% arrange(pval) %>% head(25) %>% kable(caption="Top 25 associations using a nonlinar generalized additive model, no covariates")

lm.results.anno %>% write_csv("Cholesterol - Expression Associations - GAM Model.csv")
```

# Session Information

```{r session-info}
sessionInfo()
```
