<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dave Bridges and Katie Kittell">
<meta name="dcterms.date" content="2026-08-04">

<title>Step 2 — Naive exposure → AD, then SlopeHunter selection correction</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="exposure_ad_indexevent_files/libs/clipboard/clipboard.min.js"></script>
<script src="exposure_ad_indexevent_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="exposure_ad_indexevent_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="exposure_ad_indexevent_files/libs/quarto-html/popper.min.js"></script>
<script src="exposure_ad_indexevent_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="exposure_ad_indexevent_files/libs/quarto-html/anchor.min.js"></script>
<link href="exposure_ad_indexevent_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="exposure_ad_indexevent_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="exposure_ad_indexevent_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="exposure_ad_indexevent_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="exposure_ad_indexevent_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#purpose" id="toc-purpose" class="nav-link active" data-scroll-target="#purpose">Purpose</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#configuration" id="toc-configuration" class="nav-link" data-scroll-target="#configuration">Configuration</a></li>
  <li><a href="#naive-exposure-ad-uncorrected" id="toc-naive-exposure-ad-uncorrected" class="nav-link" data-scroll-target="#naive-exposure-ad-uncorrected">Naive exposure → AD (uncorrected)</a></li>
  <li><a href="#exposure-lifespan-arm-reused-from-step-1" id="toc-exposure-lifespan-arm-reused-from-step-1" class="nav-link" data-scroll-target="#exposure-lifespan-arm-reused-from-step-1">Exposure → lifespan arm (reused from Step 1)</a></li>
  <li><a href="#selection-slope-b_sh" id="toc-selection-slope-b_sh" class="nav-link" data-scroll-target="#selection-slope-b_sh">Selection slope b_SH</a>
  <ul class="collapse">
  <li><a href="#why-the-kunkle-b_sh-is-not-used" id="toc-why-the-kunkle-b_sh-is-not-used" class="nav-link" data-scroll-target="#why-the-kunkle-b_sh-is-not-used">Why the Kunkle <code>b_SH</code> is not used</a></li>
  </ul></li>
  <li><a href="#corrected-exposure-ad" id="toc-corrected-exposure-ad" class="nav-link" data-scroll-target="#corrected-exposure-ad">Corrected exposure → AD</a></li>
  <li><a href="#naive-vs-corrected-forest" id="toc-naive-vs-corrected-forest" class="nav-link" data-scroll-target="#naive-vs-corrected-forest">Naive vs corrected — forest</a></li>
  <li><a href="#how-to-read-this" id="toc-how-to-read-this" class="nav-link" data-scroll-target="#how-to-read-this">How to read this</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="exposure_ad_indexevent.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Step 2 — Naive exposure → AD, then SlopeHunter selection correction</h1>
<p class="subtitle lead">Adjusting each exposure → AD estimate for the survival collider flagged in Step 1</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dave Bridges and Katie Kittell </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 4, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="purpose" class="level2">
<h2 class="anchored" data-anchor-id="purpose">Purpose</h2>
<p>Step 1 (<code>exposure_survival_screen.qmd</code>) established two things: (i) AD shortens survival, so the survival collider <code>S</code> is real, and (ii) for the exposures flagged there, the <code>E → S</code> arm is present — i.e.&nbsp;selecting on survival induces a spurious <code>G_exposure</code>–AD association, in a direction given by <code>sign(b_E · b_AD)</code>. This notebook does the correction: for each exposure we</p>
<ol type="1">
<li>estimate the <strong>naive</strong> <code>E → AD</code> effect (standard two-sample MR, <em>uncorrected</em> — this is the estimate that carries the survival-collider bias), then</li>
<li>subtract the selection-induced component using a <strong>SlopeHunter</strong> selection slope <code>b_SH</code>, exactly as in the smoking→AD analysis (<code>smoking/04e_overlap_indexevent.qmd</code>).</li>
</ol>
<p>Because IVW is linear, the correction is exact: <span class="math display">\[ \text{corrected}(E\to\text{AD}) \;=\; (E\to\text{AD}) \;-\; b_{SH}\,(E\to\text{lifespan}). \]</span></p>
<p><code>b_SH</code> is the SlopeHunter slope relating SNP effects on AD (prognosis) to SNP effects on lifespan (the selection axis). It is a property of the <strong>(AD GWAS × lifespan GWAS)</strong> pair and is <em>exposure-independent</em> — estimate it once per AD GWAS (<code>R/fit_selection_slope.R</code>, genome-wide, APOE excluded), then apply it to every exposure. <code>E → lifespan</code> is reused from Step 1.</p>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># cache=FALSE is required: a cached setup chunk is restored WITHOUT re-running library()/source(),</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># so on re-render dplyr etc. would not be attached ("could not find function transmute").</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(TwoSampleMR)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ieugwasr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(purrr)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Optional, needed only for those naive models: MRPRESSO (MR-PRESSO), mr.raps (MR-RAPS).</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(c("MRPRESSO", "mr.raps"))  # both used via TwoSampleMR wrappers; absent -&gt; IVW-MRE fallback</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Correction engine (correct_estimate + the genome-wide fit driver).</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"R/fit_selection_slope.R"</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">nchar</span>(ieugwasr<span class="sc">::</span><span class="fu">get_opengwas_jwt</span>()) <span class="sc">&gt;</span> <span class="dv">0</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="configuration" class="level2">
<h2 class="anchored" data-anchor-id="configuration">Configuration</h2>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Exposures + the SOP-validated naive model used for each E -&gt; AD association. ----</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># One row per exposure: OpenGWAS `id` AND the `naive_model` you validated for that association,</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># so the collider correction runs on the exact model you used — not a re-derived default.</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Model choice can be a judgement call (e.g. LDL-C: visual APOE outliers -&gt; MR-PRESSO), which is</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># why it is recorded explicitly here rather than auto-selected. `note` documents the rationale.</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Allowed `naive_model`: "IVW-FE", "IVW-MRE", "MR-Egger", "Weighted median", "Weighted mode",</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># "MR-RAPS", "MR-PRESSO"  (SOP: https://bridgeslab.sph.umich.edu/protocols/index.php/Mendelian_Randomization)</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>exposures <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tribble</span>(</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>label,                         <span class="sc">~</span>id,                  <span class="sc">~</span>naive_model,      <span class="sc">~</span>note,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Weight"</span>,                       <span class="st">"ukb-b-12039"</span>,        <span class="st">"IVW-MRE"</span>,         <span class="st">"no horizontal pleiotropy, heterogeneity"</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"BMI"</span>,                          <span class="st">"ukb-b-2303"</span>,         <span class="st">"IVW-MRE"</span>,         <span class="st">"no horizontal pleiotropy, heterogeneity"</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Fat Mass"</span>,                     <span class="st">"ukb-b-19393"</span>,        <span class="st">"IVW-MRE"</span>,         <span class="st">"no horizontal pleiotropy, heterogeneity"</span>,</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Lean Mass"</span>,                    <span class="st">"ebi-a-GCST90000025"</span>, <span class="st">"IVW-MRE"</span>,         <span class="st">"no horizontal pleiotropy, heterogeneity"</span>,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Type 2 Diabetes"</span>,              <span class="st">"ebi-a-GCST006867"</span>,   <span class="st">"IVW-MRE"</span>,         <span class="st">"no horizontal pleiotropy, heterogeneity"</span>,</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"HbA1C"</span>,                        <span class="st">"ieu-b-103"</span>,          <span class="st">"IVW-FE"</span>,          <span class="st">"no horizontal pleiotropy, no heterogeneity"</span>,</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Blood Glucose"</span>,                <span class="st">"ebi-a-GCST90025986"</span>, <span class="st">"IVW-MRE"</span>,         <span class="st">"no horizontal pleiotropy, heterogeneity"</span>,</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Fasting Blood Glucose"</span>,        <span class="st">"ebi-a-GCST005186"</span>,   <span class="st">"IVW-MRE"</span>,         <span class="st">"no horizontal pleiotropy, heterogeneity"</span>,</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Peak Blood Glucose"</span>,           <span class="st">"ebi-a-GCST90002227"</span>, <span class="st">"IVW-FE"</span>,          <span class="st">"no horizontal pleiotropy, no heterogeneity"</span>,</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>  <span class="st">"HDL Cholesterol"</span>,              <span class="st">"ieu-b-109"</span>,          <span class="st">"MR-PRESSO"</span>,       <span class="st">"visual APOE outliers -&gt; PRESSO"</span>,</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>  <span class="st">"LDL Cholesterol"</span>,              <span class="st">"ieu-b-110"</span>,          <span class="st">"MR-PRESSO"</span>,       <span class="st">"visual APOE outliers -&gt; PRESSO"</span>,</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Cardiovascular Disease"</span>,       <span class="st">"ebi-a-GCST90029019"</span>, <span class="st">"IVW-MRE"</span>,         <span class="st">"no horizontal pleiotropy, heterogeneity"</span>,</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Systolic Blood Pressure"</span>,      <span class="st">"ieu-b-5138"</span>,         <span class="st">"IVW-MRE"</span>,         <span class="st">"no horizontal pleiotropy, heterogeneity"</span>,</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Diastolic Blood Pressure"</span>,     <span class="st">"ieu-b-5139"</span>,         <span class="st">"IVW-MRE"</span>,         <span class="st">"no horizontal pleiotropy, heterogeneity"</span>,</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Spelling must match the `tsm` lookup in `run_naive_model` (matching is case-insensitive</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>  <span class="co"># since 2026-08-04; "Weighted Median" previously fell through to IVW-MRE silently).</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Chronotype"</span>,                   <span class="st">"ieu-a-1087"</span>,         <span class="st">"Weighted median"</span>, <span class="st">"why?"</span>,</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Sleep Duration"</span>,               <span class="st">"ukb-b-4424"</span>,         <span class="st">"IVW-MRE"</span>,         <span class="st">"no horizontal pleiotropy, heterogeneity"</span>,</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Sleeplessness"</span>,                <span class="st">"ukb-b-3957"</span>,         <span class="st">"IVW-FE"</span>,          <span class="st">"no horizontal pleiotropy, no heterogeneity"</span>,</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Educational Attainment (CC)"</span>,  <span class="st">"ebi-a-GCST90029012"</span>, <span class="st">"MR-RAPS"</span>,         <span class="st">"Weak Instruments (F&lt;10)"</span>,</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Educational Attainment (YOE)"</span>, <span class="st">"ebi-a-GCST90029013"</span>, <span class="st">"IVW-MRE"</span>,         <span class="st">"no horizontal pleiotropy, heterogeneity"</span>,</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Smoking (GSCAN)"</span>,              <span class="st">"ieu-b-142"</span>,          <span class="st">"MR-PRESSO"</span>,       <span class="st">"visual APOE outliers -&gt; PRESSO"</span>,</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Alcohol"</span>,                      <span class="st">"ieu-b-73"</span>,           <span class="st">"IVW-MRE"</span>,         <span class="st">"no horizontal pleiotropy, heterogeneity"</span>,</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Schizophrenia"</span>,                <span class="st">"ieu-b-5102"</span>,         <span class="st">"IVW-MRE"</span>,         <span class="st">"no horizontal pleiotropy, heterogeneity"</span>,</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Bipolar Disorder"</span>,             <span class="st">"ieu-b-5110"</span>,         <span class="st">"IVW-MRE"</span>,         <span class="st">"no horizontal pleiotropy, heterogeneity"</span>,</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Major Depressive Disorder"</span>,    <span class="st">"ieu-a-1187"</span>,         <span class="st">"IVW-MRE"</span>,         <span class="st">"no horizontal pleiotropy, heterogeneity"</span></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- AD outcomes (the downstream trait, measured only in survivors). ----</span></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>ad_gwas <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>  <span class="st">"AD — Bellenguez 2022 (proxy-incl.)"</span> <span class="ot">=</span> <span class="st">"ebi-a-GCST90027158"</span>,</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>  <span class="st">"AD — Kunkle 2019 IGAP (clinical)"</span>   <span class="ot">=</span> <span class="st">"ieu-b-2"</span></span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Selection axis = the lifespan GWAS b_SH is fit on. MUST match Step 1's PRIMARY_SURVIVAL</span></span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a><span class="co">#      and the E -&gt; lifespan estimates we reuse below. ----</span></span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>SELECTION_LABEL <span class="ot">&lt;-</span> <span class="st">"Parental lifespan (combined, Martingale resid)"</span>  <span class="co"># ebi-a-GCST006697</span></span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Selection slope b_SH per AD GWAS. ----</span></span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a><span class="co"># b_SH is genome-wide, LD-clumped, APOE-excluded (see R/fit_selection_slope.R). It is heavy to</span></span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a><span class="co"># fit (needs full sumstats), so we consume a cached fits CSV per AD GWAS. Bellenguez x this same</span></span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a><span class="co"># lifespan is already fit in the smoking pipeline; Kunkle needs its own fit (chunk below).</span></span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a><span class="co"># `trusted` gates whether a fitted b_SH is actually APPLIED. A b_SH is only meaningful if the</span></span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a><span class="co"># underlying data carry a raw selection signal — SlopeHunter returns a slope with a tight</span></span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a><span class="co"># bootstrap CI even when the two axes are unrelated (see "Why the Kunkle b_SH is not used").</span></span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a><span class="co"># Set trusted = FALSE rather than deleting the fit, so the value stays visible and the reason</span></span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a><span class="co"># travels with the table instead of living in someone's memory.</span></span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a>bsh_sources <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tribble</span>(</span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>ad_id,               <span class="sc">~</span>fits_csv,                                          <span class="sc">~</span>fit_set,              <span class="sc">~</span>trusted, <span class="sc">~</span>reason,</span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a>  <span class="st">"ebi-a-GCST90027158"</span>, <span class="st">"smoking/results/indexevent_slopehunter_fits.csv"</span>,  <span class="st">"excl_APOE (PRIMARY)"</span>, <span class="cn">TRUE</span>,     <span class="st">"validated in the smoking pipeline"</span>,</span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a>  <span class="st">"ieu-b-2"</span>,            <span class="st">"R/fits/kunkle_lifespan_slopehunter_fits.csv"</span>,      <span class="st">"excl_APOE (PRIMARY)"</span>, <span class="cn">FALSE</span>,    <span class="st">"not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs"</span></span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a><span class="co"># Instrument / clumping parameters (match Step 1).</span></span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a>P_THRESH <span class="ot">&lt;-</span> <span class="fl">5e-8</span></span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a>R2       <span class="ot">&lt;-</span> <span class="fl">0.001</span></span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a>KB       <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a><span class="co"># ROPE for judging whether a *corrected* effect is practically non-null (per-SD outcome).</span></span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a>ROPE <span class="ot">&lt;-</span> <span class="fl">0.01</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="naive-exposure-ad-uncorrected" class="level2">
<h2 class="anchored" data-anchor-id="naive-exposure-ad-uncorrected">Naive exposure → AD (uncorrected)</h2>
<p>The bias-carrying estimate. Same instrument selection as Step 1, pointed at AD.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Retry a (possibly rate-limited) OpenGWAS call with exponential backoff. `fn` is a thunk.</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>og_retry <span class="ot">&lt;-</span> <span class="cf">function</span>(fn, <span class="at">tries =</span> <span class="dv">4</span>, <span class="at">base =</span> <span class="dv">3</span>) {</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_len</span>(tries)) {</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    r <span class="ot">&lt;-</span> <span class="fu">tryCatch</span>(<span class="fu">fn</span>(), <span class="at">error =</span> <span class="cf">function</span>(e) <span class="cn">NULL</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(r) <span class="sc">&amp;&amp;</span> (<span class="sc">!</span><span class="fu">is.data.frame</span>(r) <span class="sc">||</span> <span class="fu">nrow</span>(r) <span class="sc">&gt;</span> <span class="dv">0</span>)) <span class="fu">return</span>(r)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (i <span class="sc">&lt;</span> tries) <span class="fu">Sys.sleep</span>(base <span class="sc">*</span> i)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="cn">NULL</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Instruments are pulled ONCE per exposure and reused across AD outcomes (halves API calls and</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="co"># keeps the instrument set identical across the two AD GWAS).</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>.inst_cache <span class="ot">&lt;-</span> <span class="fu">new.env</span>(<span class="at">parent =</span> <span class="fu">emptyenv</span>())</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>get_instruments <span class="ot">&lt;-</span> <span class="cf">function</span>(exp_id, p, r2, kb) {</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>  key <span class="ot">&lt;-</span> <span class="fu">paste</span>(exp_id, p, r2, kb)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.null</span>(.inst_cache[[key]]))</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>    .inst_cache[[key]] <span class="ot">&lt;-</span> <span class="fu">og_retry</span>(<span class="cf">function</span>() <span class="fu">extract_instruments</span>(exp_id, <span class="at">p1 =</span> p, <span class="at">r2 =</span> r2, <span class="at">kb =</span> kb))</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>  .inst_cache[[key]]</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Dispatch to the SOP-validated naive model on a harmonised dataset. Returns one row with the</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="co"># estimate + diagnostics (Cochran's Q p, Egger-intercept p, and — for MR-PRESSO — #outliers and</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="co"># the global-test p). Unknown/failed methods and missing optional packages (MRPRESSO, mr.raps)</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="co"># degrade to IVW-MRE, and the `method` column shows what actually ran so a fallback is visible.</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>run_naive_model <span class="ot">&lt;-</span> <span class="cf">function</span>(dat, <span class="at">model =</span> <span class="st">"IVW-MRE"</span>) {</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>  tsm <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"IVW-FE"</span> <span class="ot">=</span> <span class="st">"mr_ivw_fe"</span>, <span class="st">"IVW-MRE"</span> <span class="ot">=</span> <span class="st">"mr_ivw_mre"</span>, <span class="st">"MR-Egger"</span> <span class="ot">=</span> <span class="st">"mr_egger_regression"</span>,</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>           <span class="st">"Weighted median"</span> <span class="ot">=</span> <span class="st">"mr_weighted_median"</span>, <span class="st">"Weighted mode"</span> <span class="ot">=</span> <span class="st">"mr_weighted_mode"</span>,</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>           <span class="st">"MR-RAPS"</span> <span class="ot">=</span> <span class="st">"mr_raps"</span>)</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>  Q_p   <span class="ot">&lt;-</span> <span class="fu">tryCatch</span>(<span class="fu">mr_heterogeneity</span>(dat, <span class="at">method_list =</span> <span class="st">"mr_ivw"</span>)<span class="sc">$</span>Q_pval[<span class="dv">1</span>], <span class="at">error =</span> \(e) <span class="cn">NA_real_</span>)</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>  egg_p <span class="ot">&lt;-</span> <span class="fu">tryCatch</span>(<span class="fu">mr_pleiotropy_test</span>(dat)<span class="sc">$</span>pval,                            <span class="at">error =</span> \(e) <span class="cn">NA_real_</span>)</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Enforce column types so rows from different models always bind (list_rbind is type-strict).</span></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>  out_row <span class="ot">&lt;-</span> <span class="cf">function</span>(method, b, se, p, n, <span class="at">n_out =</span> <span class="cn">NA_integer_</span>, <span class="at">gp =</span> <span class="cn">NA_real_</span>)</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tibble</span>(<span class="at">model =</span> model, <span class="at">method =</span> method, <span class="at">n_snp =</span> <span class="fu">as.integer</span>(n),</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>           <span class="at">b =</span> <span class="fu">as.numeric</span>(b), <span class="at">se =</span> <span class="fu">as.numeric</span>(se), <span class="at">p =</span> <span class="fu">as.numeric</span>(p),</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>           <span class="at">Q_p =</span> <span class="fu">as.numeric</span>(Q_p), <span class="at">egger_int_p =</span> <span class="fu">as.numeric</span>(egg_p),</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>           <span class="at">n_outlier =</span> <span class="fu">as.integer</span>(n_out), <span class="at">presso_global_p =</span> <span class="fu">as.numeric</span>(gp))</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>  <span class="co"># MR-PRESSO reports very small p-values as strings ("&lt;0.001"); coerce to numeric so rows bind.</span></span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>  as_num <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="cf">if</span> (<span class="fu">is.character</span>(x)) <span class="fu">suppressWarnings</span>(<span class="fu">as.numeric</span>(<span class="fu">sub</span>(<span class="st">"^&lt;"</span>, <span class="st">""</span>, x))) <span class="cf">else</span> <span class="fu">as.numeric</span>(x)</span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Case-insensitive so a capitalisation slip in the config cannot silently downgrade an</span></span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>  <span class="co"># exposure to IVW-MRE. That is exactly what happened to Chronotype ("Weighted Median" vs the</span></span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>  <span class="co"># table's "Weighted median"): it ran IVW-MRE while the config claimed weighted median, AND it</span></span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a>  <span class="co"># made `cache_ok` below permanently FALSE, forcing a full 48-call OpenGWAS re-pull every render.</span></span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">toupper</span>(model) <span class="sc">==</span> <span class="st">"MR-PRESSO"</span>) {                     <span class="co"># SOP: chosen when outliers seen / Q sig</span></span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a>    pr <span class="ot">&lt;-</span> <span class="fu">tryCatch</span>(<span class="fu">suppressWarnings</span>(<span class="fu">run_mr_presso</span>(dat, <span class="at">NbDistribution =</span> <span class="dv">1000</span>,</span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>                                                  <span class="at">SignifThreshold =</span> <span class="fl">0.05</span>)), <span class="at">error =</span> \(e) <span class="cn">NULL</span>)</span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(pr)) {</span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a>      main <span class="ot">&lt;-</span> pr[[<span class="dv">1</span>]]<span class="sc">$</span><span class="st">`</span><span class="at">Main MR results</span><span class="st">`</span></span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a>      gp   <span class="ot">&lt;-</span> <span class="fu">as_num</span>(pr[[<span class="dv">1</span>]]<span class="sc">$</span><span class="st">`</span><span class="at">MR-PRESSO results</span><span class="st">`</span><span class="sc">$</span><span class="st">`</span><span class="at">Global Test</span><span class="st">`</span><span class="sc">$</span>Pvalue)</span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a>      oidx <span class="ot">&lt;-</span> pr[[<span class="dv">1</span>]]<span class="sc">$</span><span class="st">`</span><span class="at">MR-PRESSO results</span><span class="st">`</span><span class="sc">$</span><span class="st">`</span><span class="at">Distortion Test</span><span class="st">`</span><span class="sc">$</span><span class="st">`</span><span class="at">Outliers Indices</span><span class="st">`</span></span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a>      n_out <span class="ot">&lt;-</span> <span class="cf">if</span> (<span class="fu">is.null</span>(oidx)) <span class="dv">0</span>L <span class="cf">else</span> <span class="fu">length</span>(oidx)</span>
<span id="cb3-53"><a href="#cb3-53" aria-hidden="true" tabindex="-1"></a>      row <span class="ot">&lt;-</span> main[main<span class="sc">$</span><span class="st">`</span><span class="at">MR Analysis</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Outlier-corrected"</span>, ]</span>
<span id="cb3-54"><a href="#cb3-54" aria-hidden="true" tabindex="-1"></a>      lab <span class="ot">&lt;-</span> <span class="st">"MR-PRESSO (outlier-corrected)"</span></span>
<span id="cb3-55"><a href="#cb3-55" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> (<span class="fu">nrow</span>(row) <span class="sc">==</span> <span class="dv">0</span> <span class="sc">||</span> <span class="fu">is.na</span>(<span class="fu">as_num</span>(row<span class="sc">$</span><span class="st">`</span><span class="at">Causal Estimate</span><span class="st">`</span>))) {   <span class="co"># no outliers -&gt; raw estimate</span></span>
<span id="cb3-56"><a href="#cb3-56" aria-hidden="true" tabindex="-1"></a>        row <span class="ot">&lt;-</span> main[main<span class="sc">$</span><span class="st">`</span><span class="at">MR Analysis</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Raw"</span>, ]; lab <span class="ot">&lt;-</span> <span class="st">"MR-PRESSO (raw; no outliers)"</span></span>
<span id="cb3-57"><a href="#cb3-57" aria-hidden="true" tabindex="-1"></a>      }</span>
<span id="cb3-58"><a href="#cb3-58" aria-hidden="true" tabindex="-1"></a>      <span class="fu">return</span>(<span class="fu">out_row</span>(lab, <span class="fu">as_num</span>(row<span class="sc">$</span><span class="st">`</span><span class="at">Causal Estimate</span><span class="st">`</span>), <span class="fu">as_num</span>(row<span class="sc">$</span>Sd),</span>
<span id="cb3-59"><a href="#cb3-59" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">as_num</span>(row<span class="sc">$</span><span class="st">`</span><span class="at">P-value</span><span class="st">`</span>), <span class="fu">nrow</span>(dat), n_out, gp))</span>
<span id="cb3-60"><a href="#cb3-60" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb3-61"><a href="#cb3-61" aria-hidden="true" tabindex="-1"></a>    <span class="fu">message</span>(<span class="st">"MR-PRESSO unavailable/failed — falling back to IVW-MRE"</span>); model <span class="ot">&lt;-</span> <span class="st">"IVW-MRE"</span></span>
<span id="cb3-62"><a href="#cb3-62" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb3-63"><a href="#cb3-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-64"><a href="#cb3-64" aria-hidden="true" tabindex="-1"></a>  meth <span class="ot">&lt;-</span> <span class="fu">unname</span>(tsm[<span class="fu">match</span>(<span class="fu">toupper</span>(model), <span class="fu">toupper</span>(<span class="fu">names</span>(tsm)))])  <span class="co"># NA if genuinely unknown</span></span>
<span id="cb3-65"><a href="#cb3-65" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.na</span>(meth)) {</span>
<span id="cb3-66"><a href="#cb3-66" aria-hidden="true" tabindex="-1"></a>    <span class="fu">warning</span>(<span class="st">"unknown naive_model '"</span>, model, <span class="st">"' — falling back to IVW-MRE. Fix the config: "</span>,</span>
<span id="cb3-67"><a href="#cb3-67" aria-hidden="true" tabindex="-1"></a>            <span class="st">"allowed values are "</span>, <span class="fu">paste</span>(<span class="fu">names</span>(tsm), <span class="at">collapse =</span> <span class="st">", "</span>), <span class="st">", MR-PRESSO."</span>)</span>
<span id="cb3-68"><a href="#cb3-68" aria-hidden="true" tabindex="-1"></a>    model <span class="ot">&lt;-</span> <span class="st">"IVW-MRE (fallback)"</span>; meth <span class="ot">&lt;-</span> <span class="st">"mr_ivw_mre"</span></span>
<span id="cb3-69"><a href="#cb3-69" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb3-70"><a href="#cb3-70" aria-hidden="true" tabindex="-1"></a>  res <span class="ot">&lt;-</span> <span class="fu">tryCatch</span>(<span class="fu">mr</span>(dat, <span class="at">method_list =</span> meth), <span class="at">error =</span> \(e) <span class="cn">NULL</span>)</span>
<span id="cb3-71"><a href="#cb3-71" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.null</span>(res) <span class="sc">||</span> <span class="fu">nrow</span>(res) <span class="sc">==</span> <span class="dv">0</span>) {                                <span class="co"># e.g. mr.raps not installed</span></span>
<span id="cb3-72"><a href="#cb3-72" aria-hidden="true" tabindex="-1"></a>    res <span class="ot">&lt;-</span> <span class="fu">mr</span>(dat, <span class="at">method_list =</span> <span class="st">"mr_ivw_mre"</span>)</span>
<span id="cb3-73"><a href="#cb3-73" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">out_row</span>(<span class="st">"IVW-MRE (fallback)"</span>, res<span class="sc">$</span>b[<span class="dv">1</span>], res<span class="sc">$</span>se[<span class="dv">1</span>], res<span class="sc">$</span>pval[<span class="dv">1</span>], res<span class="sc">$</span>nsnp[<span class="dv">1</span>]))</span>
<span id="cb3-74"><a href="#cb3-74" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb3-75"><a href="#cb3-75" aria-hidden="true" tabindex="-1"></a>  <span class="fu">out_row</span>(model, res<span class="sc">$</span>b[<span class="dv">1</span>], res<span class="sc">$</span>se[<span class="dv">1</span>], res<span class="sc">$</span>pval[<span class="dv">1</span>], res<span class="sc">$</span>nsnp[<span class="dv">1</span>])</span>
<span id="cb3-76"><a href="#cb3-76" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-77"><a href="#cb3-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-78"><a href="#cb3-78" aria-hidden="true" tabindex="-1"></a><span class="co"># One exposure x one AD outcome: pull, harmonise, run the SOP-validated model -&gt; one estimate row.</span></span>
<span id="cb3-79"><a href="#cb3-79" aria-hidden="true" tabindex="-1"></a>mr_pair <span class="ot">&lt;-</span> <span class="cf">function</span>(exp_id, exp_label, out_id, out_label, <span class="at">model =</span> <span class="st">"IVW-MRE"</span>,</span>
<span id="cb3-80"><a href="#cb3-80" aria-hidden="true" tabindex="-1"></a>                    <span class="at">p =</span> P_THRESH, <span class="at">r2 =</span> R2, <span class="at">kb =</span> KB) {</span>
<span id="cb3-81"><a href="#cb3-81" aria-hidden="true" tabindex="-1"></a>  inst <span class="ot">&lt;-</span> <span class="fu">get_instruments</span>(exp_id, p, r2, kb)</span>
<span id="cb3-82"><a href="#cb3-82" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.null</span>(inst) <span class="sc">||</span> <span class="fu">nrow</span>(inst) <span class="sc">==</span> <span class="dv">0</span>) <span class="fu">stop</span>(<span class="st">"no instruments: "</span>, exp_id)</span>
<span id="cb3-83"><a href="#cb3-83" aria-hidden="true" tabindex="-1"></a>  out <span class="ot">&lt;-</span> <span class="fu">og_retry</span>(<span class="cf">function</span>() <span class="fu">extract_outcome_data</span>(<span class="at">snps =</span> inst<span class="sc">$</span>SNP, <span class="at">outcomes =</span> out_id))</span>
<span id="cb3-84"><a href="#cb3-84" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.null</span>(out) <span class="sc">||</span> <span class="fu">nrow</span>(out) <span class="sc">==</span> <span class="dv">0</span>) <span class="fu">stop</span>(<span class="st">"no overlap: "</span>, out_id)</span>
<span id="cb3-85"><a href="#cb3-85" aria-hidden="true" tabindex="-1"></a>  dat <span class="ot">&lt;-</span> <span class="fu">harmonise_data</span>(inst, out, <span class="at">action =</span> <span class="dv">2</span>) <span class="sc">|&gt;</span> <span class="fu">filter</span>(mr_keep)</span>
<span id="cb3-86"><a href="#cb3-86" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">nrow</span>(dat) <span class="sc">==</span> <span class="dv">0</span>) <span class="fu">stop</span>(<span class="st">"nothing kept after harmonisation"</span>)</span>
<span id="cb3-87"><a href="#cb3-87" aria-hidden="true" tabindex="-1"></a>  <span class="fu">run_naive_model</span>(dat, model) <span class="sc">|&gt;</span></span>
<span id="cb3-88"><a href="#cb3-88" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">exposure =</span> exp_label, <span class="at">ad =</span> out_label, <span class="at">.before =</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-89"><a href="#cb3-89" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">b_ad =</span> b, <span class="at">se_ad =</span> se, <span class="at">p_ad =</span> p)</span>
<span id="cb3-90"><a href="#cb3-90" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-91"><a href="#cb3-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-92"><a href="#cb3-92" aria-hidden="true" tabindex="-1"></a><span class="co"># Typed empty prototype so a fully-failed pull still carries the schema downstream joins need.</span></span>
<span id="cb3-93"><a href="#cb3-93" aria-hidden="true" tabindex="-1"></a>naive_proto <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">exposure =</span> <span class="fu">character</span>(), <span class="at">ad =</span> <span class="fu">character</span>(), <span class="at">model =</span> <span class="fu">character</span>(),</span>
<span id="cb3-94"><a href="#cb3-94" aria-hidden="true" tabindex="-1"></a>                      <span class="at">method =</span> <span class="fu">character</span>(), <span class="at">n_snp =</span> <span class="fu">integer</span>(), <span class="at">b_ad =</span> <span class="fu">double</span>(),</span>
<span id="cb3-95"><a href="#cb3-95" aria-hidden="true" tabindex="-1"></a>                      <span class="at">se_ad =</span> <span class="fu">double</span>(), <span class="at">p_ad =</span> <span class="fu">double</span>(), <span class="at">Q_p =</span> <span class="fu">double</span>(),</span>
<span id="cb3-96"><a href="#cb3-96" aria-hidden="true" tabindex="-1"></a>                      <span class="at">egger_int_p =</span> <span class="fu">double</span>(), <span class="at">n_outlier =</span> <span class="fu">integer</span>(), <span class="at">presso_global_p =</span> <span class="fu">double</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>naive_grid <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  exposures <span class="sc">|&gt;</span> <span class="fu">transmute</span>(<span class="at">exp_id =</span> id, <span class="at">exp_label =</span> label, <span class="at">model =</span> naive_model),</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">out_id =</span> <span class="fu">unname</span>(ad_gwas), <span class="at">out_label =</span> <span class="fu">names</span>(ad_gwas))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Persist the successful pull to CSV rather than knitr cache: an empty/failed pull is never</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># written, so a later render retries once the OpenGWAS allowance is back.</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>naive_csv <span class="ot">&lt;-</span> <span class="st">"exposure_ad_naive.csv"</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-pull if the cache is missing, predates the schema, OR was computed under different</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co"># `naive_model` choices than the config now requests — so changing a model auto-invalidates it.</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>cache_ok <span class="ot">&lt;-</span> <span class="fu">local</span>({</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">file.exists</span>(naive_csv)) <span class="fu">return</span>(<span class="cn">FALSE</span>)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  hdr <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">read_csv</span>(naive_csv, <span class="at">n_max =</span> <span class="dv">0</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>))</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">all</span>(<span class="fu">c</span>(<span class="st">"exposure"</span>, <span class="st">"model"</span>, <span class="st">"b_ad"</span>, <span class="st">"se_ad"</span>, <span class="st">"p_ad"</span>, <span class="st">"n_outlier"</span>, <span class="st">"Q_p"</span>) <span class="sc">%in%</span> hdr))</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="cn">FALSE</span>)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>  cached    <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(naive_csv, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span> <span class="fu">distinct</span>(exposure, model)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>  requested <span class="ot">&lt;-</span> exposures <span class="sc">|&gt;</span> <span class="fu">transmute</span>(<span class="at">exposure =</span> label, <span class="at">model =</span> naive_model)</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nrow</span>(<span class="fu">anti_join</span>(requested, cached, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"exposure"</span>, <span class="st">"model"</span>))) <span class="sc">==</span> <span class="dv">0</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>naive_ad <span class="ot">&lt;-</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (cache_ok) {</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">read_csv</span>(naive_csv, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>    x <span class="ot">&lt;-</span> <span class="fu">pmap</span>(naive_grid, <span class="fu">possibly</span>(mr_pair, <span class="at">otherwise =</span> <span class="cn">NULL</span>)) <span class="sc">|&gt;</span> <span class="fu">compact</span>() <span class="sc">|&gt;</span> <span class="fu">list_rbind</span>()</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">nrow</span>(x) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>      <span class="fu">write_csv</span>(x, naive_csv); x</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> {</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>      <span class="fu">warning</span>(<span class="st">"Naive E→AD returned no rows — OpenGWAS is likely rate-limited or the token's "</span>,</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>              <span class="st">"allowance is exhausted. Check ieugwasr::user(); rerun once available. The "</span>,</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>              <span class="st">"correction below will be empty until then."</span>)</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>      naive_proto</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>naive_ad <span class="sc">|&gt;</span></span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(exposure, ad, model, method, n_snp, b_ad, se_ad, p_ad, n_outlier, Q_p) <span class="sc">|&gt;</span></span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), \(x) <span class="fu">signif</span>(x, <span class="dv">3</span>))) <span class="sc">|&gt;</span></span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Naive exposure → AD, per SOP-validated model (n_outlier / Q p = MR-PRESSO / heterogeneity diagnostics)."</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Naive exposure → AD, per SOP-validated model (n_outlier / Q p = MR-PRESSO / heterogeneity diagnostics).</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 21%">
<col style="width: 9%">
<col style="width: 18%">
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">exposure</th>
<th style="text-align: left;">ad</th>
<th style="text-align: left;">model</th>
<th style="text-align: left;">method</th>
<th style="text-align: right;">n_snp</th>
<th style="text-align: right;">b_ad</th>
<th style="text-align: right;">se_ad</th>
<th style="text-align: right;">p_ad</th>
<th style="text-align: right;">n_outlier</th>
<th style="text-align: right;">Q_p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Weight</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">470</td>
<td style="text-align: right;">-0.16700</td>
<td style="text-align: right;">0.03210</td>
<td style="text-align: right;">2.00e-07</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Weight</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">397</td>
<td style="text-align: right;">-0.16400</td>
<td style="text-align: right;">0.06480</td>
<td style="text-align: right;">1.12e-02</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BMI</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">429</td>
<td style="text-align: right;">-0.12400</td>
<td style="text-align: right;">0.03300</td>
<td style="text-align: right;">1.80e-04</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">BMI</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">371</td>
<td style="text-align: right;">-0.24200</td>
<td style="text-align: right;">0.16300</td>
<td style="text-align: right;">1.37e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fat Mass</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">414</td>
<td style="text-align: right;">-0.17000</td>
<td style="text-align: right;">0.03200</td>
<td style="text-align: right;">1.00e-07</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fat Mass</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">362</td>
<td style="text-align: right;">-0.33700</td>
<td style="text-align: right;">0.17100</td>
<td style="text-align: right;">4.87e-02</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lean Mass</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">608</td>
<td style="text-align: right;">-0.10100</td>
<td style="text-align: right;">0.02190</td>
<td style="text-align: right;">4.10e-06</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lean Mass</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">528</td>
<td style="text-align: right;">-0.13000</td>
<td style="text-align: right;">0.03910</td>
<td style="text-align: right;">8.99e-04</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">5.70e-06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Type 2 Diabetes</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">115</td>
<td style="text-align: right;">-0.00508</td>
<td style="text-align: right;">0.01830</td>
<td style="text-align: right;">7.81e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Type 2 Diabetes</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">108</td>
<td style="text-align: right;">-0.01020</td>
<td style="text-align: right;">0.02770</td>
<td style="text-align: right;">7.14e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.51e-05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HbA1C</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-FE</td>
<td style="text-align: left;">IVW-FE</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0.08140</td>
<td style="text-align: right;">0.07970</td>
<td style="text-align: right;">3.07e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">7.25e-01</td>
</tr>
<tr class="even">
<td style="text-align: left;">HbA1C</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-FE</td>
<td style="text-align: left;">IVW-FE</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0.26100</td>
<td style="text-align: right;">0.14400</td>
<td style="text-align: right;">6.96e-02</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">8.38e-01</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Blood Glucose</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">113</td>
<td style="text-align: right;">-0.00215</td>
<td style="text-align: right;">0.04810</td>
<td style="text-align: right;">9.64e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Blood Glucose</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">98</td>
<td style="text-align: right;">0.04270</td>
<td style="text-align: right;">0.07330</td>
<td style="text-align: right;">5.60e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.60e-06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fasting Blood Glucose</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">0.02400</td>
<td style="text-align: right;">0.08530</td>
<td style="text-align: right;">7.79e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.59e-03</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fasting Blood Glucose</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">0.14100</td>
<td style="text-align: right;">0.22000</td>
<td style="text-align: right;">5.21e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">5.00e-06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Peak Blood Glucose</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-FE</td>
<td style="text-align: left;">IVW-FE</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0.08590</td>
<td style="text-align: right;">0.03640</td>
<td style="text-align: right;">1.83e-02</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">9.83e-02</td>
</tr>
<tr class="even">
<td style="text-align: left;">Peak Blood Glucose</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-FE</td>
<td style="text-align: left;">IVW-FE</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0.05440</td>
<td style="text-align: right;">0.07180</td>
<td style="text-align: right;">4.48e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">6.90e-01</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HDL Cholesterol</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">MR-PRESSO</td>
<td style="text-align: left;">MR-PRESSO (outlier-corrected)</td>
<td style="text-align: right;">314</td>
<td style="text-align: right;">0.10000</td>
<td style="text-align: right;">0.02440</td>
<td style="text-align: right;">5.15e-05</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">HDL Cholesterol</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">MR-PRESSO</td>
<td style="text-align: left;">MR-PRESSO (outlier-corrected)</td>
<td style="text-align: right;">291</td>
<td style="text-align: right;">-0.03360</td>
<td style="text-align: right;">0.04870</td>
<td style="text-align: right;">4.91e-01</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LDL Cholesterol</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">MR-PRESSO</td>
<td style="text-align: left;">MR-PRESSO (outlier-corrected)</td>
<td style="text-align: right;">161</td>
<td style="text-align: right;">-0.07530</td>
<td style="text-align: right;">0.03390</td>
<td style="text-align: right;">2.78e-02</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">LDL Cholesterol</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">MR-PRESSO</td>
<td style="text-align: left;">MR-PRESSO (outlier-corrected)</td>
<td style="text-align: right;">149</td>
<td style="text-align: right;">0.02290</td>
<td style="text-align: right;">0.06660</td>
<td style="text-align: right;">7.32e-01</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cardiovascular Disease</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">213</td>
<td style="text-align: right;">-0.56600</td>
<td style="text-align: right;">0.11600</td>
<td style="text-align: right;">1.00e-06</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cardiovascular Disease</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">181</td>
<td style="text-align: right;">0.36100</td>
<td style="text-align: right;">0.35900</td>
<td style="text-align: right;">3.15e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Systolic Blood Pressure</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">243</td>
<td style="text-align: right;">-0.00668</td>
<td style="text-align: right;">0.00278</td>
<td style="text-align: right;">1.63e-02</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Systolic Blood Pressure</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">216</td>
<td style="text-align: right;">-0.00278</td>
<td style="text-align: right;">0.00424</td>
<td style="text-align: right;">5.12e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.14e-04</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diastolic Blood Pressure</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">254</td>
<td style="text-align: right;">-0.01750</td>
<td style="text-align: right;">0.00452</td>
<td style="text-align: right;">1.11e-04</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diastolic Blood Pressure</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">214</td>
<td style="text-align: right;">-0.01980</td>
<td style="text-align: right;">0.00727</td>
<td style="text-align: right;">6.46e-03</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4.68e-03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chronotype</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">Weighted median</td>
<td style="text-align: left;">Weighted median</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.22800</td>
<td style="text-align: right;">0.16900</td>
<td style="text-align: right;">1.79e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.01e-01</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chronotype</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">Weighted median</td>
<td style="text-align: left;">Weighted median</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.08340</td>
<td style="text-align: right;">0.29300</td>
<td style="text-align: right;">7.76e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">9.49e-01</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sleep Duration</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">-0.11100</td>
<td style="text-align: right;">0.15300</td>
<td style="text-align: right;">4.67e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sleep Duration</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">-0.02820</td>
<td style="text-align: right;">0.25600</td>
<td style="text-align: right;">9.12e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4.15e-05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sleeplessness</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-FE</td>
<td style="text-align: left;">IVW-FE</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">0.07000</td>
<td style="text-align: right;">0.13100</td>
<td style="text-align: right;">5.94e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">4.68e-01</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sleeplessness</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-FE</td>
<td style="text-align: left;">IVW-FE</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">-0.08890</td>
<td style="text-align: right;">0.25800</td>
<td style="text-align: right;">7.31e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.60e-01</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Educational Attainment (CC)</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">MR-RAPS</td>
<td style="text-align: left;">MR-RAPS</td>
<td style="text-align: right;">203</td>
<td style="text-align: right;">0.09040</td>
<td style="text-align: right;">0.12200</td>
<td style="text-align: right;">4.58e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Educational Attainment (CC)</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">MR-RAPS</td>
<td style="text-align: left;">MR-RAPS</td>
<td style="text-align: right;">181</td>
<td style="text-align: right;">-0.64100</td>
<td style="text-align: right;">0.20900</td>
<td style="text-align: right;">2.14e-03</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.02e-03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Educational Attainment (YOE)</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">211</td>
<td style="text-align: right;">0.01500</td>
<td style="text-align: right;">0.01100</td>
<td style="text-align: right;">1.74e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Educational Attainment (YOE)</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">185</td>
<td style="text-align: right;">-0.05390</td>
<td style="text-align: right;">0.01840</td>
<td style="text-align: right;">3.44e-03</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.07e-03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Smoking (GSCAN)</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">MR-PRESSO</td>
<td style="text-align: left;">MR-PRESSO (outlier-corrected)</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-0.11200</td>
<td style="text-align: right;">0.03050</td>
<td style="text-align: right;">1.47e-03</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Smoking (GSCAN)</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">MR-PRESSO</td>
<td style="text-align: left;">MR-PRESSO (raw; no outliers)</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">-0.02630</td>
<td style="text-align: right;">0.07080</td>
<td style="text-align: right;">7.14e-01</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4.16e-02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alcohol</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">0.12200</td>
<td style="text-align: right;">0.12800</td>
<td style="text-align: right;">3.42e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alcohol</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">0.16600</td>
<td style="text-align: right;">0.21400</td>
<td style="text-align: right;">4.40e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.14e-05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Schizophrenia</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">0.03800</td>
<td style="text-align: right;">0.01640</td>
<td style="text-align: right;">2.05e-02</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Schizophrenia</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">131</td>
<td style="text-align: right;">0.03170</td>
<td style="text-align: right;">0.02450</td>
<td style="text-align: right;">1.97e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.04e-02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bipolar Disorder</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">0.10400</td>
<td style="text-align: right;">0.02860</td>
<td style="text-align: right;">2.64e-04</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">5.34e-04</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bipolar Disorder</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">0.01120</td>
<td style="text-align: right;">0.04670</td>
<td style="text-align: right;">8.11e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.01e-02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Major Depressive Disorder</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">-0.03520</td>
<td style="text-align: right;">0.07470</td>
<td style="text-align: right;">6.37e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.78e-05</td>
</tr>
<tr class="even">
<td style="text-align: left;">Major Depressive Disorder</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">-0.08770</td>
<td style="text-align: right;">0.12400</td>
<td style="text-align: right;">4.79e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.00e-03</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Model selection (scatter/funnel inspection, MR-PRESSO vs IVW-MRE vs …) was done when these associations were first identified; the validated choice is recorded in <code>naive_model</code> above and applied here. This notebook only carries the correction.</p>
</section>
<section id="exposure-lifespan-arm-reused-from-step-1" class="level2">
<h2 class="anchored" data-anchor-id="exposure-lifespan-arm-reused-from-step-1">Exposure → lifespan arm (reused from Step 1)</h2>
<p><code>E → lifespan</code> on the same selection axis <code>b_SH</code> is fit on. Read from Step 1’s saved screen; if that file is absent, recompute with the same function.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Sign convention: this axis increases with MORTALITY, not with lifespan.</strong> <code>GCST006697</code> is a Martingale residual from a Cox model for death, so a <em>positive</em> beta means <em>shorter</em> life. Verified two ways: in the raw sumstats every established AD risk allele is positive (<code>rs429358</code>/C +0.057, <code>rs6656401</code>/A +0.007, <code>rs6733839</code>/T +0.007) and the ε2 longevity allele <code>rs7412</code>/T is negative; and in Step 1’s output every harmful exposure is positive (CVD +0.60, smoking +0.10, BMI +0.14, LDL +0.065) while protective ones are negative (education −0.38, HDL −0.066). So <code>E→life = +0.6</code> for CVD reads “CVD raises mortality”, <strong>not</strong> “CVD extends life”.</p>
<p><code>b_SH</code> and <code>b_life</code> are both taken from this same axis, so the subtraction <code>b_ad − b_SH · b_life</code> is internally consistent — <strong>do not “fix” this by negating one term</strong>, which would silently break the correction. The column is named <code>b_life</code> for continuity with Step 1.</p>
<p>One consequence worth noting: on a mortality-increasing axis, survival-collider bias predicts a <strong>negative</strong> <code>b_SH</code> (alleles that raise mortality deplete their carriers before AD can be ascertained, so they look protective for AD). Bellenguez’s <code>−0.944</code> has that expected sign; Kunkle’s <code>+1.10</code> does not — a further reason to distrust it, alongside the identifiability failure documented below.</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1 keys exposures by source-tagged name; this notebook keys by `label`.</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Map explicitly rather than fuzzy-matching — the tags encode which GWAS was used.</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>step1_key <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tribble</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>label,                         <span class="sc">~</span>exposure_step1,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Weight"</span>,                       <span class="st">"weight.ukb"</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"BMI"</span>,                          <span class="st">"BMI.elsworth"</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Fat Mass"</span>,                     <span class="st">"fatmass.elsworth"</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Lean Mass IS in Step 1, but only against other survival traits — it has no row on</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># SELECTION_LABEL, the axis b_SH is fit on. Mapped here so the crosswalk is complete and the</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># gap is attributed to the missing axis (below) rather than to a missing key.</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Lean Mass"</span>,                    <span class="st">"leanmass.pei"</span>,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Type 2 Diabetes"</span>,              <span class="st">"T2D.xue"</span>,</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"HbA1C"</span>,                        <span class="st">"HbA1C.soranzo"</span>,</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Blood Glucose"</span>,                <span class="st">"bloodglucose.barton"</span>,</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Fasting Blood Glucose"</span>,        <span class="st">"FBG.manning"</span>,</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Peak Blood Glucose"</span>,           <span class="st">"PBG.chen"</span>,</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"HDL Cholesterol"</span>,              <span class="st">"HDLchol.ukb.richardson"</span>,</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"LDL Cholesterol"</span>,              <span class="st">"LDLchol.ukb.richardson"</span>,</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Cardiovascular Disease"</span>,       <span class="st">"CVD.loh"</span>,</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Systolic Blood Pressure"</span>,      <span class="st">"SBP.tang"</span>,</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Diastolic Blood Pressure"</span>,     <span class="st">"DBP.tang"</span>,</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Chronotype"</span>,                   <span class="st">"chronotype.ukbb"</span>,</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Sleep Duration"</span>,               <span class="st">"sleepduration.elsworth"</span>,</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Sleeplessness"</span>,                <span class="st">"sleeplessness.elsworth"</span>,</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Educational Attainment (CC)"</span>,  <span class="st">"EA.collegecomplete"</span>,</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Educational Attainment (YOE)"</span>, <span class="st">"EA.yearsofed"</span>,</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Smoking (GSCAN)"</span>,              <span class="st">"cig.liu"</span>,</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Alcohol"</span>,                      <span class="st">"alcohol.liu"</span>,</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Schizophrenia"</span>,                <span class="st">"schizophrenia.pgc"</span>,</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Bipolar Disorder"</span>,             <span class="st">"bipolar.pgc"</span>,</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Major Depressive Disorder"</span>,    <span class="st">"MDD.pgc"</span></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>es_arm <span class="ot">&lt;-</span></span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">file.exists</span>(<span class="st">"exposure_survival_screen.csv"</span>)) {</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>    <span class="fu">read_csv</span>(<span class="st">"exposure_survival_screen.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(survival <span class="sc">==</span> SELECTION_LABEL) <span class="sc">|&gt;</span></span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>      <span class="fu">inner_join</span>(step1_key, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"exposure"</span> <span class="ot">=</span> <span class="st">"exposure_step1"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>      <span class="fu">transmute</span>(<span class="at">exposure =</span> label, <span class="at">b_life =</span> b, <span class="at">se_life =</span> se, <span class="at">p_life =</span> p)</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>    <span class="fu">warning</span>(<span class="st">"exposure_survival_screen.csv not found — recomputing E → lifespan (IVW-MRE)."</span>)</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>    life_id <span class="ot">&lt;-</span> <span class="st">"ebi-a-GCST006697"</span></span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>    exp_tbl <span class="ot">&lt;-</span> exposures <span class="sc">|&gt;</span> <span class="fu">transmute</span>(<span class="at">exp_id =</span> id, <span class="at">exp_label =</span> label)</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pmap</span>(exp_tbl, \(exp_id, exp_label)</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>         <span class="fu">possibly</span>(mr_pair, <span class="cn">NULL</span>)(exp_id, exp_label, life_id, SELECTION_LABEL)) <span class="sc">|&gt;</span></span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>      <span class="fu">compact</span>() <span class="sc">|&gt;</span> <span class="fu">list_rbind</span>() <span class="sc">|&gt;</span></span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>      <span class="fu">transmute</span>(exposure, <span class="at">b_life =</span> b_ad, <span class="at">se_life =</span> se_ad, <span class="at">p_life =</span> p_ad)</span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a><span class="co"># Fail LOUDLY on a broken join. A silent key mismatch here yields b_life = NA for every row,</span></span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a><span class="co"># which propagates to b_corr = NA and an all-gaps corrected table — the failure this notebook</span></span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a><span class="co"># previously mis-reported as a missing b_SH. Separate the two causes so the fix is obvious:</span></span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a><span class="co">#   - not in `step1_key`      -&gt; add a crosswalk row</span></span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a><span class="co">#   - in the key, no CSV row  -&gt; run Step 1 for that exposure on SELECTION_LABEL</span></span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a>missing_life <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(exposures<span class="sc">$</span>label, es_arm<span class="sc">$</span>exposure)</span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(missing_life)) {</span>
<span id="cb5-57"><a href="#cb5-57" aria-hidden="true" tabindex="-1"></a>  unmapped <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(missing_life, step1_key<span class="sc">$</span>label)</span>
<span id="cb5-58"><a href="#cb5-58" aria-hidden="true" tabindex="-1"></a>  no_axis  <span class="ot">&lt;-</span> <span class="fu">intersect</span>(missing_life, step1_key<span class="sc">$</span>label)</span>
<span id="cb5-59"><a href="#cb5-59" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(unmapped))</span>
<span id="cb5-60"><a href="#cb5-60" aria-hidden="true" tabindex="-1"></a>    <span class="fu">warning</span>(<span class="st">"NOT IN step1_key (add a crosswalk row): "</span>, <span class="fu">paste</span>(unmapped, <span class="at">collapse =</span> <span class="st">", "</span>))</span>
<span id="cb5-61"><a href="#cb5-61" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(no_axis))</span>
<span id="cb5-62"><a href="#cb5-62" aria-hidden="true" tabindex="-1"></a>    <span class="fu">warning</span>(<span class="st">"no Step 1 row on '"</span>, SELECTION_LABEL, <span class="st">"' (rerun Step 1 for these): "</span>,</span>
<span id="cb5-63"><a href="#cb5-63" aria-hidden="true" tabindex="-1"></a>            <span class="fu">paste</span>(no_axis, <span class="at">collapse =</span> <span class="st">", "</span>))</span>
<span id="cb5-64"><a href="#cb5-64" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-65"><a href="#cb5-65" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">nrow</span>(es_arm) <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb5-66"><a href="#cb5-66" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stop</span>(<span class="st">"es_arm is empty — the Step 1 join matched nothing. Check `step1_key` against "</span>,</span>
<span id="cb5-67"><a href="#cb5-67" aria-hidden="true" tabindex="-1"></a>       <span class="st">"`unique(read_csv('exposure_survival_screen.csv')$exposure)` and that SELECTION_LABEL "</span>,</span>
<span id="cb5-68"><a href="#cb5-68" aria-hidden="true" tabindex="-1"></a>       <span class="st">"matches a value of the `survival` column."</span>)</span>
<span id="cb5-69"><a href="#cb5-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-70"><a href="#cb5-70" aria-hidden="true" tabindex="-1"></a>es_arm <span class="sc">|&gt;</span></span>
<span id="cb5-71"><a href="#cb5-71" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), \(x) <span class="fu">signif</span>(x, <span class="dv">3</span>))) <span class="sc">|&gt;</span></span>
<span id="cb5-72"><a href="#cb5-72" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Exposure → lifespan (selection axis), from Step 1."</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Exposure → lifespan (selection axis), from Step 1.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">exposure</th>
<th style="text-align: right;">b_life</th>
<th style="text-align: right;">se_life</th>
<th style="text-align: right;">p_life</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Chronotype</td>
<td style="text-align: right;">-0.00327</td>
<td style="text-align: right;">0.043200</td>
<td style="text-align: right;">0.94000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sleeplessness</td>
<td style="text-align: right;">-0.01520</td>
<td style="text-align: right;">0.051600</td>
<td style="text-align: right;">0.76900</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sleep Duration</td>
<td style="text-align: right;">-0.07080</td>
<td style="text-align: right;">0.040800</td>
<td style="text-align: right;">0.08260</td>
</tr>
<tr class="even">
<td style="text-align: left;">LDL Cholesterol</td>
<td style="text-align: right;">0.06500</td>
<td style="text-align: right;">0.010600</td>
<td style="text-align: right;">0.00000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HDL Cholesterol</td>
<td style="text-align: right;">-0.06560</td>
<td style="text-align: right;">0.008860</td>
<td style="text-align: right;">0.00000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Weight</td>
<td style="text-align: right;">0.10400</td>
<td style="text-align: right;">0.010100</td>
<td style="text-align: right;">0.00000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fasting Blood Glucose</td>
<td style="text-align: right;">0.03510</td>
<td style="text-align: right;">0.017700</td>
<td style="text-align: right;">0.04760</td>
</tr>
<tr class="even">
<td style="text-align: left;">Peak Blood Glucose</td>
<td style="text-align: right;">0.02090</td>
<td style="text-align: right;">0.012900</td>
<td style="text-align: right;">0.10400</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Type 2 Diabetes</td>
<td style="text-align: right;">0.02730</td>
<td style="text-align: right;">0.004940</td>
<td style="text-align: right;">0.00000</td>
</tr>
<tr class="even">
<td style="text-align: left;">BMI</td>
<td style="text-align: right;">0.13600</td>
<td style="text-align: right;">0.011100</td>
<td style="text-align: right;">0.00000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Blood Glucose</td>
<td style="text-align: right;">0.01430</td>
<td style="text-align: right;">0.010700</td>
<td style="text-align: right;">0.18100</td>
</tr>
<tr class="even">
<td style="text-align: left;">HbA1C</td>
<td style="text-align: right;">-0.01800</td>
<td style="text-align: right;">0.037600</td>
<td style="text-align: right;">0.63200</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Schizophrenia</td>
<td style="text-align: right;">0.00582</td>
<td style="text-align: right;">0.005380</td>
<td style="text-align: right;">0.28000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Major Depressive Disorder</td>
<td style="text-align: right;">-0.00869</td>
<td style="text-align: right;">0.023000</td>
<td style="text-align: right;">0.70600</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bipolar Disorder</td>
<td style="text-align: right;">-0.02210</td>
<td style="text-align: right;">0.007080</td>
<td style="text-align: right;">0.00177</td>
</tr>
<tr class="even">
<td style="text-align: left;">Systolic Blood Pressure</td>
<td style="text-align: right;">0.01000</td>
<td style="text-align: right;">0.000812</td>
<td style="text-align: right;">0.00000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diastolic Blood Pressure</td>
<td style="text-align: right;">0.01640</td>
<td style="text-align: right;">0.001410</td>
<td style="text-align: right;">0.00000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Educational Attainment (YOE)</td>
<td style="text-align: right;">-0.03480</td>
<td style="text-align: right;">0.003020</td>
<td style="text-align: right;">0.00000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Educational Attainment (CC)</td>
<td style="text-align: right;">-0.38400</td>
<td style="text-align: right;">0.032500</td>
<td style="text-align: right;">0.00000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cardiovascular Disease</td>
<td style="text-align: right;">0.60300</td>
<td style="text-align: right;">0.030100</td>
<td style="text-align: right;">0.00000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Smoking (GSCAN)</td>
<td style="text-align: right;">0.10200</td>
<td style="text-align: right;">0.017700</td>
<td style="text-align: right;">0.00000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alcohol</td>
<td style="text-align: right;">0.08870</td>
<td style="text-align: right;">0.039700</td>
<td style="text-align: right;">0.02560</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fat Mass</td>
<td style="text-align: right;">0.12700</td>
<td style="text-align: right;">0.011800</td>
<td style="text-align: right;">0.00000</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="selection-slope-b_sh" class="level2">
<h2 class="anchored" data-anchor-id="selection-slope-b_sh">Selection slope b_SH</h2>
<p>One genome-wide, APOE-excluded SlopeHunter slope per AD GWAS. Bellenguez × this lifespan is reused from the smoking pipeline; a missing fit (e.g.&nbsp;Kunkle before you run the driver) yields <code>NA</code> and its exposures are reported as a gap rather than silently left uncorrected.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Returns the fitted value in `b_SH_fitted` (always, for display) and in `b_SH` (the column the</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># correction consumes) ONLY when trusted. An untrusted fit therefore propagates as b_corr = NA</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># and is reported as an explicit gap, never silently applied.</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>load_bsh <span class="ot">&lt;-</span> <span class="cf">function</span>(ad_id) {</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  src <span class="ot">&lt;-</span> bsh_sources <span class="sc">|&gt;</span> <span class="fu">filter</span>(ad_id <span class="sc">==</span> <span class="sc">!!</span>ad_id)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  na_row <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">ad_id =</span> ad_id, <span class="at">b_SH_fitted =</span> <span class="cn">NA_real_</span>, <span class="at">se_SH_fitted =</span> <span class="cn">NA_real_</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">n_fit =</span> <span class="cn">NA_integer_</span>, <span class="at">trusted =</span> <span class="cn">FALSE</span>, <span class="at">reason =</span> <span class="st">"no fits CSV — run the driver"</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">nrow</span>(src) <span class="sc">==</span> <span class="dv">0</span> <span class="sc">||</span> <span class="sc">!</span><span class="fu">file.exists</span>(src<span class="sc">$</span>fits_csv[<span class="dv">1</span>])) <span class="fu">return</span>(na_row)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(src<span class="sc">$</span>fits_csv[<span class="dv">1</span>], <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(set <span class="sc">==</span> src<span class="sc">$</span>fit_set[<span class="dv">1</span>]) <span class="sc">|&gt;</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">transmute</span>(<span class="at">ad_id =</span> ad_id, <span class="at">b_SH_fitted =</span> b_SH, <span class="at">se_SH_fitted =</span> se_SH,</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>              <span class="at">n_fit =</span> dplyr<span class="sc">::</span><span class="fu">coalesce</span>(n_fit, <span class="cn">NA_integer_</span>)) <span class="sc">|&gt;</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">slice</span>(<span class="dv">1</span>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">nrow</span>(fit) <span class="sc">==</span> <span class="dv">0</span>) <span class="fu">return</span>(na_row)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  fit <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">trusted =</span> src<span class="sc">$</span>trusted[<span class="dv">1</span>], <span class="at">reason =</span> src<span class="sc">$</span>reason[<span class="dv">1</span>])</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>bsh <span class="ot">&lt;-</span> <span class="fu">map</span>(<span class="fu">unname</span>(ad_gwas), load_bsh) <span class="sc">|&gt;</span> <span class="fu">list_rbind</span>() <span class="sc">|&gt;</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(<span class="fu">tibble</span>(<span class="at">ad_id =</span> <span class="fu">unname</span>(ad_gwas), <span class="at">ad =</span> <span class="fu">names</span>(ad_gwas)), <span class="at">by =</span> <span class="st">"ad_id"</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">b_SH  =</span> <span class="fu">if_else</span>(trusted, b_SH_fitted,  <span class="cn">NA_real_</span>),</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>         <span class="at">se_SH =</span> <span class="fu">if_else</span>(trusted, se_SH_fitted, <span class="cn">NA_real_</span>))</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>bsh <span class="sc">|&gt;</span></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(<span class="st">`</span><span class="at">AD GWAS</span><span class="st">`</span> <span class="ot">=</span> ad, <span class="st">`</span><span class="at">b_SH (fitted)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">signif</span>(b_SH_fitted, <span class="dv">3</span>),</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>            <span class="at">se_SH =</span> <span class="fu">signif</span>(se_SH_fitted, <span class="dv">3</span>), n_fit,</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>            <span class="at">applied =</span> <span class="fu">if_else</span>(trusted, <span class="st">"yes"</span>, <span class="st">"NO"</span>), reason) <span class="sc">|&gt;</span></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">caption =</span> <span class="fu">paste0</span>(</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SlopeHunter selection slope b_SH (genome-wide, APOE excluded). A fit is applied only if "</span>,</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>    <span class="st">"the raw data carry a selection signal — see 'Why the Kunkle b_SH is not used'."</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>SlopeHunter selection slope b_SH (genome-wide, APOE excluded). A fit is applied only if the raw data carry a selection signal — see ‘Why the Kunkle b_SH is not used’.</caption>
<colgroup>
<col style="width: 23%">
<col style="width: 9%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">AD GWAS</th>
<th style="text-align: right;">b_SH (fitted)</th>
<th style="text-align: right;">se_SH</th>
<th style="text-align: right;">n_fit</th>
<th style="text-align: left;">applied</th>
<th style="text-align: left;">reason</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">0.0701</td>
<td style="text-align: right;">2250</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">validated in the smoking pipeline</td>
</tr>
<tr class="even">
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: right;">1.100</td>
<td style="text-align: right;">0.1120</td>
<td style="text-align: right;">2250</td>
<td style="text-align: left;">NO</td>
<td style="text-align: left;">not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>To fit <code>b_SH</code> for an AD GWAS that has no cached fit yet (needs full sumstats + plink2 clumping — see <code>smoking/scripts/fetch_sumstats.sh</code>):</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Turnkey: `bash scripts/fetch_kunkle_sumstats.sh` downloads + normalizes the Kunkle and</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># lifespan sumstats and the LD panel, then prints the prep + `plink2 --clump` commands. After</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># clumping, this single call preps, filters to the clumped set, fits, and writes the fits CSV:</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="st">"R/fits"</span>, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>, <span class="at">recursive =</span> <span class="cn">TRUE</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">build_selection_slope</span>(</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ad_file      =</span> <span class="st">"data/cache/sumstats/AD_kunkle_harmonised.tsv.gz"</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">life_file    =</span> <span class="st">"data/cache/sumstats/LIFESPAN_pilling_harmonised.tsv.gz"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">clumped_snps =</span> <span class="st">"data/cache/sumstats/kunkle_clumped.clumps"</span>,  <span class="co"># plink2 --clump output</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">out_csv      =</span> <span class="st">"R/fits/kunkle_lifespan_slopehunter_fits.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="why-the-kunkle-b_sh-is-not-used" class="level3">
<h3 class="anchored" data-anchor-id="why-the-kunkle-b_sh-is-not-used">Why the Kunkle <code>b_SH</code> is not used</h3>
<p>The Kunkle fit returns <code>b_SH = +1.10 (SE 0.112)</code>, opposite in sign to the validated Bellenguez <code>−0.944</code>. Two candidate explanations were tested, and a third was found.</p>
<p><strong>1. Allele inversion in the Kunkle sumstats — ruled out.</strong> <code>rs429358</code> carries effect allele <code>T</code> with <code>beta = −1.202</code> (<code>p = 1.2e-881</code>), i.e.&nbsp;the <code>C</code>/ε4 allele is <code>+1.20</code> — correct. <code>rs6656401</code>/A (CR1), <code>rs6733839</code>/T (BIN1), <code>rs11136000</code>/T (CLU) and <code>rs3851179</code>/T (PICALM) all match published directions. The file is correctly oriented, so the sign is not an orientation artefact. (Reusable check below.)</p>
<p><strong>2. A different sign convention between the two fits — ruled out.</strong> Both fits use the same lifespan file (<code>GCST006697</code>) and identical prep code (<code>smoking/R/prep_indexevent_genomewide.R</code> vs <code>prep_selection_merge()</code> here); neither negates <code>beta_life</code>. Both clump on the <em>lifespan</em> axis, which is why the two fits share <code>n_fit = 2250</code> — that agreement is expected, not suspicious.</p>
<p><strong>3. The actual cause — <code>b_SH</code> is not identified in Kunkle.</strong> On the exact SNPs SlopeHunter fits (<code>p_life &lt; 1e-3</code>, APOE excluded, n = 2250), the raw relationship between lifespan and Kunkle AD effects is <em>absent</em>: Pearson <em>r</em> = −0.0008, OLS slope −0.002, sign agreement 0.499 — a coin flip. There is no survival-collider signal in the data for the model to recover. SlopeHunter nonetheless returns a slope, because its mixture model always partitions the cloud it is given; with no signal, the “hunted” cluster is carved out of noise. The estimate is perfectly stable across 20 seeds (SD = 0) and flips to exactly <code>−1.101</code> when the AD betas are negated, so the fit is a faithful, deterministic function of its input — there is no bug. It is simply describing noise geometry, not a selection slope.</p>
<p>Two further checks agree. Block-permuting the AD statistics (a guaranteed null) returns <code>b_SH ≈ −0.73</code>, confirming that <strong>this model’s no-signal output is a large non-zero slope</strong>, so the tight CI around <code>+1.10</code> carries no evidential weight. And on a mortality-increasing axis, survival-collider bias predicts a <em>negative</em> <code>b_SH</code> (see the sign-convention note above) — <code>+1.10</code> has the wrong sign for the mechanism it is supposed to be measuring.</p>
<p>This is the expected regime for Kunkle: clinical-only ascertainment at ~63k is both less powered and — by design — carries less survival-driven structure than a proxy-inclusive GWAS. That absence is the <em>substantive result</em>, and it is the same point the Task B comparison makes. So we report the Kunkle column <strong>uncorrected</strong> and let the raw Bellenguez-vs-Kunkle attenuation carry the argument, rather than subtracting a slope estimated from noise.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Never apply a <code>b_SH</code> without checking identifiability first.</strong> A slope fitted to noise will <em>manufacture</em> corrected effects — including significant UNMASKED and REVERSED verdicts — out of true nulls, and its bootstrap CI gives no warning. Run <code>bsh_identifiability()</code> on every new AD GWAS before trusting its <code>b_SH</code>.</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># (a) Orientation — needs only the one AD file, so it runs even when a second AD GWAS is not</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># on disk (the two-file `ad_orientation_check()` could not: no local Bellenguez sumstats).</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>oc <span class="ot">&lt;-</span> <span class="fu">check_ad_orientation_anchors</span>(<span class="st">"data/cache/sumstats/AD_kunkle_harmonised.tsv.gz"</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>oc; <span class="fu">attr</span>(oc, <span class="st">"verdict"</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># (b) Identifiability — is there any raw selection signal for SlopeHunter to find?</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>m_kunk <span class="ot">&lt;-</span> <span class="fu">prep_selection_merge</span>(<span class="st">"data/cache/sumstats/AD_kunkle_harmonised.tsv.gz"</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"data/cache/sumstats/LIFESPAN_pilling_harmonised.tsv.gz"</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>ct <span class="ot">&lt;-</span> data.table<span class="sc">::</span><span class="fu">fread</span>(<span class="st">"data/cache/sumstats/kunkle_clumped.clumps"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>prim <span class="ot">&lt;-</span> m_kunk[SNP <span class="sc">%in%</span> ct<span class="sc">$</span>ID][apoe <span class="sc">==</span> <span class="cn">FALSE</span>]</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="fu">bsh_identifiability</span>(prim)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="co"># (c) Null distribution — what does SlopeHunter return when there is provably no relationship?</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare |observed b_SH| against this spread, NOT against the bootstrap CI. (~2 min.)</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a><span class="fu">bsh_null_permutation</span>(prim, <span class="at">n_perm =</span> <span class="dv">8</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Run (a)–(c) on the Bellenguez merge too</strong> — see caveat 0 under “How to read this”. The <code>−0.944</code> currently being applied has passed neither (b) nor (c); it is inherited from the smoking pipeline, where those checks did not exist. <code>AD_bellenguez_harmonised.tsv.gz</code> is not on disk here; <code>bash smoking/scripts/fetch_sumstats.sh</code> refetches it.</p>
</div>
</div>
</section>
</section>
<section id="corrected-exposure-ad" class="level2">
<h2 class="anchored" data-anchor-id="corrected-exposure-ad">Corrected exposure → AD</h2>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>joined <span class="ot">&lt;-</span> naive_ad <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(es_arm, <span class="at">by =</span> <span class="st">"exposure"</span>) <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(bsh <span class="sc">|&gt;</span> <span class="fu">select</span>(ad, b_SH, se_SH, trusted, reason), <span class="at">by =</span> <span class="st">"ad"</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># correct_estimate() is vectorized, so call it once on whole columns. This is NA-safe (b_SH NA</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># -&gt; b_corr NA) and empty-safe (0 rows in -&gt; a 0-row tibble that still carries b_corr etc.),</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># unlike a per-row list-column + unnest() which cannot materialize columns from zero elements.</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>corrected <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  joined,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correct_estimate</span>(joined<span class="sc">$</span>b_ad, joined<span class="sc">$</span>se_ad, joined<span class="sc">$</span>b_life, joined<span class="sc">$</span>se_life,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>                   joined<span class="sc">$</span>b_SH, joined<span class="sc">$</span>se_SH)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">attenuation =</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">abs</span>(b_corr) <span class="sc">/</span> <span class="fu">abs</span>(b_uncorr),</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">verdict =</span> <span class="fu">case_when</span>(</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>      <span class="co"># `trusted` is FALSE for an unusable fit and NA if `ad` failed to join bsh at all.</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>      <span class="sc">!</span><span class="fu">coalesce</span>(trusted, <span class="cn">FALSE</span>) <span class="sc">~</span> <span class="fu">paste0</span>(<span class="st">"NOT CORRECTED — "</span>,</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>                                         <span class="fu">coalesce</span>(reason, <span class="st">"no b_SH for this AD GWAS"</span>)),</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>      <span class="fu">is.na</span>(b_SH)                                     <span class="sc">~</span> <span class="st">"no b_SH — run the fit for this AD GWAS"</span>,</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>      <span class="fu">is.na</span>(b_life)                                   <span class="sc">~</span> <span class="st">"no E→lifespan — check Step 1 join key"</span>,</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>      <span class="fu">is.na</span>(b_corr)                                   <span class="sc">~</span> <span class="st">"correction failed — inspect inputs"</span>,</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>      <span class="fu">sign</span>(b_corr) <span class="sc">!=</span> <span class="fu">sign</span>(b_uncorr) <span class="sc">&amp;</span> p_corr <span class="sc">&lt;</span> <span class="fl">0.05</span>  <span class="sc">~</span> <span class="st">"REVERSED after correction"</span>,</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>      p_ad <span class="sc">&gt;=</span> <span class="fl">0.05</span> <span class="sc">&amp;</span> p_corr <span class="sc">&lt;</span> <span class="fl">0.05</span>                    <span class="sc">~</span> <span class="st">"UNMASKED — null naive, significant after correction"</span>,</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>      p_ad <span class="sc">&lt;</span> <span class="fl">0.05</span> <span class="sc">&amp;</span> p_corr <span class="sc">&gt;=</span> <span class="fl">0.05</span>                    <span class="sc">~</span> <span class="st">"ABOLISHED — signal explained by survival bias"</span>,</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>      p_corr <span class="sc">&lt;</span> <span class="fl">0.05</span>                                   <span class="sc">~</span> <span class="st">"ROBUST — survives correction"</span>,</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span>                                            <span class="sc">~</span> <span class="st">"inconclusive"</span></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>corrected <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    exposure, <span class="st">`</span><span class="at">AD GWAS</span><span class="st">`</span> <span class="ot">=</span> ad, model, n_snp,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">naive =</span> <span class="fu">signif</span>(b_ad, <span class="dv">3</span>), <span class="st">`</span><span class="at">p naive</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">signif</span>(p_ad, <span class="dv">2</span>),</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># `b_SH` is blank wherever the fit was not applied; `verdict` carries the reason.</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">b_SH =</span> <span class="fu">signif</span>(b_SH, <span class="dv">3</span>), <span class="st">`</span><span class="at">E→life</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">signif</span>(b_life, <span class="dv">3</span>),</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">corrected =</span> <span class="fu">signif</span>(b_corr, <span class="dv">3</span>),</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">corr 95% CI</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(b_corr), <span class="cn">NA</span>,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">sprintf</span>(<span class="st">"[%.3f, %.3f]"</span>, ci_lo, ci_hi)),</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">p corr</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">signif</span>(p_corr, <span class="dv">2</span>),</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">% attenuated</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(attenuation), <span class="cn">NA</span>, <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> attenuation)),</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    verdict</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">caption =</span> <span class="fu">paste0</span>(</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Naive vs SlopeHunter-corrected exposure → AD. "</span>,</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"corrected = naive − b_SH × (E→lifespan)."</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Naive vs SlopeHunter-corrected exposure → AD. corrected = naive − b_SH × (E→lifespan).</caption>
<colgroup>
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 6%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 6%">
<col style="width: 2%">
<col style="width: 5%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">exposure</th>
<th style="text-align: left;">AD GWAS</th>
<th style="text-align: left;">model</th>
<th style="text-align: right;">n_snp</th>
<th style="text-align: right;">naive</th>
<th style="text-align: right;">p naive</th>
<th style="text-align: right;">b_SH</th>
<th style="text-align: right;">E→life</th>
<th style="text-align: right;">corrected</th>
<th style="text-align: left;">corr 95% CI</th>
<th style="text-align: right;">p corr</th>
<th style="text-align: right;">% attenuated</th>
<th style="text-align: left;">verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Weight</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">470</td>
<td style="text-align: right;">-0.16700</td>
<td style="text-align: right;">2.0e-07</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">0.10400</td>
<td style="text-align: right;">-0.06910</td>
<td style="text-align: left;">[-0.136, -0.002]</td>
<td style="text-align: right;">0.0440</td>
<td style="text-align: right;">59</td>
<td style="text-align: left;">ROBUST — survives correction</td>
</tr>
<tr class="even">
<td style="text-align: left;">Weight</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">397</td>
<td style="text-align: right;">-0.16400</td>
<td style="text-align: right;">1.1e-02</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.10400</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BMI</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">429</td>
<td style="text-align: right;">-0.12400</td>
<td style="text-align: right;">1.8e-04</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">0.13600</td>
<td style="text-align: right;">0.00517</td>
<td style="text-align: left;">[-0.065, 0.076]</td>
<td style="text-align: right;">0.8900</td>
<td style="text-align: right;">96</td>
<td style="text-align: left;">ABOLISHED — signal explained by survival bias</td>
</tr>
<tr class="even">
<td style="text-align: left;">BMI</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">371</td>
<td style="text-align: right;">-0.24200</td>
<td style="text-align: right;">1.4e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.13600</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fat Mass</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">414</td>
<td style="text-align: right;">-0.17000</td>
<td style="text-align: right;">1.0e-07</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">0.12700</td>
<td style="text-align: right;">-0.05070</td>
<td style="text-align: left;">[-0.119, 0.018]</td>
<td style="text-align: right;">0.1500</td>
<td style="text-align: right;">70</td>
<td style="text-align: left;">ABOLISHED — signal explained by survival bias</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fat Mass</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">362</td>
<td style="text-align: right;">-0.33700</td>
<td style="text-align: right;">4.9e-02</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.12700</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lean Mass</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">608</td>
<td style="text-align: right;">-0.10100</td>
<td style="text-align: right;">4.1e-06</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">no E→lifespan — check Step 1 join key</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lean Mass</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">528</td>
<td style="text-align: right;">-0.13000</td>
<td style="text-align: right;">9.0e-04</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Type 2 Diabetes</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">115</td>
<td style="text-align: right;">-0.00508</td>
<td style="text-align: right;">7.8e-01</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">0.02730</td>
<td style="text-align: right;">0.02060</td>
<td style="text-align: left;">[-0.017, 0.058]</td>
<td style="text-align: right;">0.2800</td>
<td style="text-align: right;">-306</td>
<td style="text-align: left;">inconclusive</td>
</tr>
<tr class="even">
<td style="text-align: left;">Type 2 Diabetes</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">108</td>
<td style="text-align: right;">-0.01020</td>
<td style="text-align: right;">7.1e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.02730</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HbA1C</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-FE</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0.08140</td>
<td style="text-align: right;">3.1e-01</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">-0.01800</td>
<td style="text-align: right;">0.06440</td>
<td style="text-align: left;">[-0.107, 0.235]</td>
<td style="text-align: right;">0.4600</td>
<td style="text-align: right;">21</td>
<td style="text-align: left;">inconclusive</td>
</tr>
<tr class="even">
<td style="text-align: left;">HbA1C</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-FE</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0.26100</td>
<td style="text-align: right;">7.0e-02</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.01800</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Blood Glucose</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">113</td>
<td style="text-align: right;">-0.00215</td>
<td style="text-align: right;">9.6e-01</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">0.01430</td>
<td style="text-align: right;">0.01140</td>
<td style="text-align: left;">[-0.085, 0.108]</td>
<td style="text-align: right;">0.8200</td>
<td style="text-align: right;">-427</td>
<td style="text-align: left;">inconclusive</td>
</tr>
<tr class="even">
<td style="text-align: left;">Blood Glucose</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">98</td>
<td style="text-align: right;">0.04270</td>
<td style="text-align: right;">5.6e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.01430</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fasting Blood Glucose</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">0.02400</td>
<td style="text-align: right;">7.8e-01</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">0.03510</td>
<td style="text-align: right;">0.05710</td>
<td style="text-align: left;">[-0.113, 0.228]</td>
<td style="text-align: right;">0.5100</td>
<td style="text-align: right;">-138</td>
<td style="text-align: left;">inconclusive</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fasting Blood Glucose</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">0.14100</td>
<td style="text-align: right;">5.2e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.03510</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Peak Blood Glucose</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-FE</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0.08590</td>
<td style="text-align: right;">1.8e-02</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">0.02090</td>
<td style="text-align: right;">0.10600</td>
<td style="text-align: left;">[0.030, 0.181]</td>
<td style="text-align: right;">0.0059</td>
<td style="text-align: right;">-23</td>
<td style="text-align: left;">ROBUST — survives correction</td>
</tr>
<tr class="even">
<td style="text-align: left;">Peak Blood Glucose</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-FE</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0.05440</td>
<td style="text-align: right;">4.5e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.02090</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HDL Cholesterol</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">MR-PRESSO</td>
<td style="text-align: right;">314</td>
<td style="text-align: right;">0.10000</td>
<td style="text-align: right;">5.2e-05</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">-0.06560</td>
<td style="text-align: right;">0.03840</td>
<td style="text-align: left;">[-0.013, 0.090]</td>
<td style="text-align: right;">0.1400</td>
<td style="text-align: right;">62</td>
<td style="text-align: left;">ABOLISHED — signal explained by survival bias</td>
</tr>
<tr class="even">
<td style="text-align: left;">HDL Cholesterol</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">MR-PRESSO</td>
<td style="text-align: right;">291</td>
<td style="text-align: right;">-0.03360</td>
<td style="text-align: right;">4.9e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.06560</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LDL Cholesterol</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">MR-PRESSO</td>
<td style="text-align: right;">161</td>
<td style="text-align: right;">-0.07530</td>
<td style="text-align: right;">2.8e-02</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">0.06500</td>
<td style="text-align: right;">-0.01400</td>
<td style="text-align: left;">[-0.084, 0.056]</td>
<td style="text-align: right;">0.6900</td>
<td style="text-align: right;">81</td>
<td style="text-align: left;">ABOLISHED — signal explained by survival bias</td>
</tr>
<tr class="even">
<td style="text-align: left;">LDL Cholesterol</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">MR-PRESSO</td>
<td style="text-align: right;">149</td>
<td style="text-align: right;">0.02290</td>
<td style="text-align: right;">7.3e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.06500</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cardiovascular Disease</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">213</td>
<td style="text-align: right;">-0.56600</td>
<td style="text-align: right;">1.1e-06</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">0.60300</td>
<td style="text-align: right;">0.00313</td>
<td style="text-align: left;">[-0.245, 0.251]</td>
<td style="text-align: right;">0.9800</td>
<td style="text-align: right;">99</td>
<td style="text-align: left;">ABOLISHED — signal explained by survival bias</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cardiovascular Disease</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">181</td>
<td style="text-align: right;">0.36100</td>
<td style="text-align: right;">3.1e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.60300</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Systolic Blood Pressure</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">243</td>
<td style="text-align: right;">-0.00668</td>
<td style="text-align: right;">1.6e-02</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">0.01000</td>
<td style="text-align: right;">0.00277</td>
<td style="text-align: left;">[-0.003, 0.009]</td>
<td style="text-align: right;">0.3500</td>
<td style="text-align: right;">59</td>
<td style="text-align: left;">ABOLISHED — signal explained by survival bias</td>
</tr>
<tr class="even">
<td style="text-align: left;">Systolic Blood Pressure</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">216</td>
<td style="text-align: right;">-0.00278</td>
<td style="text-align: right;">5.1e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.01000</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diastolic Blood Pressure</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">254</td>
<td style="text-align: right;">-0.01750</td>
<td style="text-align: right;">1.1e-04</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">0.01640</td>
<td style="text-align: right;">-0.00202</td>
<td style="text-align: left;">[-0.012, 0.007]</td>
<td style="text-align: right;">0.6800</td>
<td style="text-align: right;">88</td>
<td style="text-align: left;">ABOLISHED — signal explained by survival bias</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diastolic Blood Pressure</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">214</td>
<td style="text-align: right;">-0.01980</td>
<td style="text-align: right;">6.5e-03</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.01640</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chronotype</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">Weighted median</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.22800</td>
<td style="text-align: right;">1.8e-01</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">-0.00327</td>
<td style="text-align: right;">0.22500</td>
<td style="text-align: left;">[-0.117, 0.566]</td>
<td style="text-align: right;">0.2000</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">inconclusive</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chronotype</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">Weighted median</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.08340</td>
<td style="text-align: right;">7.8e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.00327</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sleep Duration</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">-0.11100</td>
<td style="text-align: right;">4.7e-01</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">-0.07080</td>
<td style="text-align: right;">-0.17800</td>
<td style="text-align: left;">[-0.488, 0.132]</td>
<td style="text-align: right;">0.2600</td>
<td style="text-align: right;">-60</td>
<td style="text-align: left;">inconclusive</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sleep Duration</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">-0.02820</td>
<td style="text-align: right;">9.1e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.07080</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sleeplessness</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-FE</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">0.07000</td>
<td style="text-align: right;">5.9e-01</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">-0.01520</td>
<td style="text-align: right;">0.05560</td>
<td style="text-align: left;">[-0.219, 0.330]</td>
<td style="text-align: right;">0.6900</td>
<td style="text-align: right;">20</td>
<td style="text-align: left;">inconclusive</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sleeplessness</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-FE</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">-0.08890</td>
<td style="text-align: right;">7.3e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.01520</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Educational Attainment (CC)</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">MR-RAPS</td>
<td style="text-align: right;">203</td>
<td style="text-align: right;">0.09040</td>
<td style="text-align: right;">4.6e-01</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">-0.38400</td>
<td style="text-align: right;">-0.27200</td>
<td style="text-align: left;">[-0.524, -0.021]</td>
<td style="text-align: right;">0.0340</td>
<td style="text-align: right;">-201</td>
<td style="text-align: left;">REVERSED after correction</td>
</tr>
<tr class="even">
<td style="text-align: left;">Educational Attainment (CC)</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">MR-RAPS</td>
<td style="text-align: right;">181</td>
<td style="text-align: right;">-0.64100</td>
<td style="text-align: right;">2.1e-03</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.38400</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Educational Attainment (YOE)</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">211</td>
<td style="text-align: right;">0.01500</td>
<td style="text-align: right;">1.7e-01</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">-0.03480</td>
<td style="text-align: right;">-0.01790</td>
<td style="text-align: left;">[-0.041, 0.005]</td>
<td style="text-align: right;">0.1300</td>
<td style="text-align: right;">-19</td>
<td style="text-align: left;">inconclusive</td>
</tr>
<tr class="even">
<td style="text-align: left;">Educational Attainment (YOE)</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">185</td>
<td style="text-align: right;">-0.05390</td>
<td style="text-align: right;">3.4e-03</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.03480</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Smoking (GSCAN)</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">MR-PRESSO</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">-0.11200</td>
<td style="text-align: right;">1.5e-03</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">0.10200</td>
<td style="text-align: right;">-0.01640</td>
<td style="text-align: left;">[-0.086, 0.053]</td>
<td style="text-align: right;">0.6500</td>
<td style="text-align: right;">85</td>
<td style="text-align: left;">ABOLISHED — signal explained by survival bias</td>
</tr>
<tr class="even">
<td style="text-align: left;">Smoking (GSCAN)</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">MR-PRESSO</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">-0.02630</td>
<td style="text-align: right;">7.1e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.10200</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alcohol</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">0.12200</td>
<td style="text-align: right;">3.4e-01</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">0.08870</td>
<td style="text-align: right;">0.20600</td>
<td style="text-align: left;">[-0.057, 0.468]</td>
<td style="text-align: right;">0.1200</td>
<td style="text-align: right;">-69</td>
<td style="text-align: left;">inconclusive</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alcohol</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">0.16600</td>
<td style="text-align: right;">4.4e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.08870</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Schizophrenia</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">0.03800</td>
<td style="text-align: right;">2.1e-02</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">0.00582</td>
<td style="text-align: right;">0.04350</td>
<td style="text-align: left;">[0.010, 0.077]</td>
<td style="text-align: right;">0.0110</td>
<td style="text-align: right;">-14</td>
<td style="text-align: left;">ROBUST — survives correction</td>
</tr>
<tr class="even">
<td style="text-align: left;">Schizophrenia</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">131</td>
<td style="text-align: right;">0.03170</td>
<td style="text-align: right;">2.0e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.00582</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bipolar Disorder</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">0.10400</td>
<td style="text-align: right;">2.6e-04</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">-0.02210</td>
<td style="text-align: right;">0.08330</td>
<td style="text-align: left;">[0.026, 0.141]</td>
<td style="text-align: right;">0.0046</td>
<td style="text-align: right;">20</td>
<td style="text-align: left;">ROBUST — survives correction</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bipolar Disorder</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">0.01120</td>
<td style="text-align: right;">8.1e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.02210</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Major Depressive Disorder</td>
<td style="text-align: left;">AD — Bellenguez 2022 (proxy-incl.)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">-0.03520</td>
<td style="text-align: right;">6.4e-01</td>
<td style="text-align: right;">-0.944</td>
<td style="text-align: right;">-0.00869</td>
<td style="text-align: right;">-0.04340</td>
<td style="text-align: left;">[-0.196, 0.109]</td>
<td style="text-align: right;">0.5800</td>
<td style="text-align: right;">-23</td>
<td style="text-align: left;">inconclusive</td>
</tr>
<tr class="even">
<td style="text-align: left;">Major Depressive Disorder</td>
<td style="text-align: left;">AD — Kunkle 2019 IGAP (clinical)</td>
<td style="text-align: left;">IVW-MRE</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">-0.08770</td>
<td style="text-align: right;">4.8e-01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.00869</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NOT CORRECTED — not identified: raw r = -0.0008, sign agreement 0.499 on the 2250 fitted SNPs</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="naive-vs-corrected-forest" class="level2">
<h2 class="anchored" data-anchor-id="naive-vs-corrected-forest">Naive vs corrected — forest</h2>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>plot_df <span class="ot">&lt;-</span> corrected <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(b_corr))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">nrow</span>(plot_df) <span class="sc">==</span> <span class="dv">0</span>) {</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">message</span>(<span class="st">"No corrected estimates to plot yet (naive pull empty or b_SH unavailable)."</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  plot_df <span class="sc">|&gt;</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">lab =</span> <span class="fu">paste</span>(exposure, ad, <span class="at">sep =</span> <span class="st">" → "</span>)) <span class="sc">|&gt;</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(lab, <span class="at">Naive =</span> b_ad, <span class="at">Corrected =</span> b_corr,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">se_n =</span> se_ad, <span class="at">se_c =</span> se_corr) <span class="sc">|&gt;</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_longer</span>(<span class="fu">c</span>(Naive, Corrected), <span class="at">names_to =</span> <span class="st">"estimate"</span>, <span class="at">values_to =</span> <span class="st">"b"</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">se =</span> <span class="fu">if_else</span>(estimate <span class="sc">==</span> <span class="st">"Naive"</span>, se_n, se_c)) <span class="sc">|&gt;</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(b, lab, <span class="at">colour =</span> estimate)) <span class="sc">+</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="dv">2</span>, <span class="at">colour =</span> <span class="st">"grey50"</span>) <span class="sc">+</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> b <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se, <span class="at">xmax =</span> b <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se),</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>                    <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="at">Naive =</span> <span class="st">"#ffcb05"</span>, <span class="at">Corrected =</span> <span class="st">"#00274c"</span>)) <span class="sc">+</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"effect on AD (log-OR)"</span>, <span class="at">y =</span> <span class="cn">NULL</span>, <span class="at">colour =</span> <span class="cn">NULL</span>,</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="st">"Survival-collider correction of exposure → AD"</span>) <span class="sc">+</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>)</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figures/forest-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="how-to-read-this" class="level2">
<h2 class="anchored" data-anchor-id="how-to-read-this">How to read this</h2>
<ul>
<li><strong>ABOLISHED</strong> — the naive effect is explained by the survival collider: after removing <code>b_SH · (E→lifespan)</code> the corrected CI covers 0. Do not treat the naive <code>E → AD</code> effect as causal/druggable (this was the smoking→AD verdict).</li>
<li><strong>ROBUST</strong> — significant before <em>and</em> after; the collider does not account for it (though see caveats).</li>
<li><strong>UNMASKED</strong> — the naive was null but the corrected effect is significant. The collider was <em>suppressing</em> a real effect: <code>naive = true + bias</code>, and here the bias ≈ −true, so the two cancelled to ~0 until correction removed the bias. A null naive never means “no effect” — the collider can hide one.</li>
<li><strong>REVERSED</strong> — correction flips the sign; the induced bias dominated the naive.</li>
</ul>
<p><strong>Trust caveat for UNMASKED/REVERSED.</strong> These “revealed” effects are only as reliable as <code>b_SH</code> and <code>E→lifespan</code>. A wrong selection slope (e.g.&nbsp;a mis-oriented <code>b_SH</code>) can <em>manufacture</em> a significant corrected effect out of a true null just as easily as it can reveal a real one — so verify the inputs (allele orientation, <code>b_SH</code> sign) before believing an UNMASKED result.</p>
<p>The <code>induced_bias</code> direction from Step 1 predicts <em>which way</em> the naive estimate is pulled; this step quantifies <em>how much</em>. They should agree in sign: a “spurious PROTECTION” flag in Step 1 means correction should move the naive <code>E → AD</code> estimate in the harmful (less protective) direction.</p>
<p>Caveats carried from Step 1 and the smoking analysis:</p>
<ol start="0" type="1">
<li><p><strong>OUTSTANDING — the null value of <code>b_SH</code> is not zero, and Bellenguez has not been checked against it.</strong> Block-permuting the Kunkle data (AD <code>beta</code>/<code>se</code>/<code>p</code> shuffled together, so any real relationship is destroyed by construction) still returns a stable <code>b_SH ≈ −0.73</code> (range −0.73 to −0.53, SD 0.074). The bootstrap SE is not misleadingly narrow — it is the <em>reference point</em> that is wrong. <strong>“<code>b_SH</code> differs significantly from 0” is therefore not evidence of selection</strong>, and every <code>b_SH</code> must be compared against its own permutation null instead.</p>
<p>This matters directly: the applied Bellenguez <code>−0.944</code> is close to the value the Kunkle geometry produces from pure noise. The two GWAS have different error structure so the null does not transfer exactly, but <strong><code>−0.944</code> cannot be treated as validated until <code>bsh_null_permutation()</code> is run on the Bellenguez merge</strong>. That needs <code>AD_bellenguez_harmonised.tsv.gz</code>, not currently on disk (<code>bash smoking/scripts/fetch_sumstats.sh</code> refetches it).</p>
<p>Until then the Bellenguez corrected column is <strong>provisional</strong>. The ABOLISHED verdicts are its robust part — they report that a naive signal fails to survive, which a noisy <code>b_SH</code> makes harder rather than easier — whereas the REVERSED (Educational Attainment CC) and any UNMASKED verdicts should be held back pending that check, per the trust caveat above.</p></li>
<li><p><strong>b_SH is per AD GWAS.</strong> Bellenguez (proxy-inclusive) and Kunkle (clinical) can carry different selection slopes; fit each rather than reusing one.</p></li>
<li><p><strong>The correction cannot separate collider-induced association from a genuine effect collinear with the mortality axis</strong> — strong evidence, not proof.</p></li>
<li><p><strong><code>E → lifespan</code> uses kin-proxy parental lifespan</strong> (~halved per-allele effects), so the subtracted term is conservative.</p></li>
</ol>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(corrected, <span class="st">"exposure_ad_indexevent_corrected.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>